#!/usr/bin/env bash
#
# git hook to run a command before actually pushing when running `git push`:
#

# Prevent pushing to "main"-branch:
if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then
  echo "You shouldn't push directly to the 'main'-branch."
  echo "Create a feature branch:  git branch new-branch-name"
  echo "Then reset 'main':        git reset --hard origin/main"
  echo "And continue to work:     git checkout new-branch-name"
  exit 1
fi


check_if_need_to_test() {
  if git diff --cached --name-only | grep --quiet "$1*"
  then
    cd "$(git rev-parse --show-toplevel)" || exit
    npm run lint --if-present --prefix "$1"
    npm test --prefix "$1"
  fi
}

# Include all packages/applications that support an `npm test` task:
check_if_need_to_test "interfaces/Portal/"
check_if_need_to_test "services/121-service/"
check_if_need_to_test "services/mock-service/"
