#!/usr/bin/env bash
#
# git hook to run a command before actually committing when running `git commit`:
#

check_if_need_to_lint() {
  if git diff --cached --name-only | grep --quiet "$1*"
  then
    cd $(git rev-parse --show-toplevel)
    cd $1 && npm run lint
  fi
}

# Include all packages/applications that support an `npm run lint` task:
check_if_need_to_lint "interfaces/PA-App/"
check_if_need_to_lint "interfaces/AW-App/"
check_if_need_to_lint "interfaces/HO-Portal/"


# Warn about files to keep in sync:
#
# warn:         `tput setaf 3`
# standout:     `tput smso`
# standout End: `tput rmso`
# reset:        `tput sgr0`

check_if_need_to_be_in_sync() {
  if git diff --cached --name-only | grep --quiet "$1*"
  then
    echo " "
    echo "$(tput setaf 3)$(tput smso) ! $(tput sgr0) Make sure to keep $(tput smso) $1 $(tput sgr0) in sync between all interfaces!"
    echo " "
  fi
}

check_if_need_to_be_in_sync "app/shared/dialogue-turn"
check_if_need_to_be_in_sync "app/services/jwt.service"
check_if_need_to_be_in_sync "app/services/api.service"
check_if_need_to_be_in_sync "app/services/translatable-string"

