import { inject, Injectable, LOCALE_ID } from '@angular/core';

import { RegistrationPreferredLanguage } from '@121-service/src/shared/enum/registration-preferred-language.enum';
import { UILanguage } from '@121-service/src/shared/enum/ui-language.enum';
import { RegistrationPreferredLanguageTranslationFull } from '@121-service/src/shared/types/registration-preferred-language-translation-full.type';

import { getUILanguageFromLocale, Locale } from '~/utils/locale';

// Linguonym = the proper name of a language.
// Just an alias, but better name locally.
type languageCodeToLinguonym = RegistrationPreferredLanguageTranslationFull;

// So, a map from language codes to linguonyms, for English.
// The other mappings are below.
const en: languageCodeToLinguonym = {
  ab: 'Abkhazian',
  aa: 'Afar',
  af: 'Afrikaans',
  ak: 'Akan',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  an: 'Aragonese',
  hy: 'Armenian',
  as: 'Assamese',
  av: 'Avaric',
  ae: 'Avestan',
  ay: 'Aymara',
  az: 'Azerbaijani',
  bm: 'Bambara',
  ba: 'Bashkir',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bi: 'Bislama',
  bs: 'Bosnian',
  br: 'Breton',
  bg: 'Bulgarian',
  my: 'Burmese',
  ca: 'Catalan, Valencian',
  ch: 'Chamorro',
  ce: 'Chechen',
  ny: 'Chichewa, Chewa, Nyanja',
  zh: 'Chinese',
  cu: 'Church Slavonic, Old Slavonic, Old Church Slavonic',
  cv: 'Chuvash',
  kw: 'Cornish',
  co: 'Corsican',
  cr: 'Cree',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  dv: 'Divehi, Dhivehi, Maldivian',
  nl: 'Dutch, Flemish',
  dz: 'Dzongkha',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  ee: 'Ewe',
  fo: 'Faroese',
  fj: 'Fijian',
  fi: 'Finnish',
  fr: 'French',
  fy: 'Western Frisian',
  ff: 'Fulah',
  gd: 'Gaelic, Scottish Gaelic',
  gl: 'Galician',
  lg: 'Ganda',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek, Modern (1453-)',
  kl: 'Kalaallisut, Greenlandic',
  gn: 'Guarani',
  gu: 'Gujarati',
  ht: 'Haitian, Haitian Creole',
  ha: 'Hausa',
  he: 'Hebrew',
  hz: 'Herero',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hu: 'Hungarian',
  is: 'Icelandic',
  io: 'Ido',
  ig: 'Igbo',
  id: 'Indonesian',
  ia: 'Interlingua (International Auxiliary Language Association)',
  ie: 'Interlingue, Occidental',
  iu: 'Inuktitut',
  ik: 'Inupiaq',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  jv: 'Javanese',
  kn: 'Kannada',
  kr: 'Kanuri',
  ks: 'Kashmiri',
  kk: 'Kazakh',
  km: 'Central Khmer',
  ki: 'Kikuyu, Gikuyu',
  rw: 'Kinyarwanda',
  ky: 'Kyrgyz, Kirghiz',
  kv: 'Komi',
  kg: 'Kongo',
  ko: 'Korean',
  kj: 'Kuanyama, Kwanyama',
  ku: 'Kurdish',
  lo: 'Lao',
  la: 'Latin',
  lv: 'Latvian',
  li: 'Limburgan, Limburger, Limburgish',
  ln: 'Lingala',
  lt: 'Lithuanian',
  lu: 'Luba-Katanga',
  lb: 'Luxembourgish, Letzeburgesch',
  mk: 'Macedonian',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  gv: 'Manx',
  mi: 'Maori',
  mr: 'Marathi',
  mh: 'Marshallese',
  mn: 'Mongolian',
  na: 'Nauru',
  nv: 'Navajo, Navaho',
  nd: 'North Ndebele',
  nr: 'South Ndebele',
  ng: 'Ndonga',
  ne: 'Nepali',
  no: 'Norwegian',
  nb: 'Norwegian Bokmål',
  nn: 'Norwegian Nynorsk',
  oc: 'Occitan',
  oj: 'Ojibwa',
  or: 'Oriya',
  om: 'Oromo',
  os: 'Ossetian, Ossetic',
  pi: 'Pali',
  ps: 'Pashto, Pushto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi, Panjabi',
  qu: 'Quechua',
  ro: 'Romanian, Moldavian, Moldovan',
  rm: 'Romansh',
  rn: 'Rundi',
  ru: 'Russian',
  se: 'Northern Sami',
  sm: 'Samoan',
  sg: 'Sango',
  sa: 'Sanskrit',
  sc: 'Sardinian',
  sr: 'Serbian',
  sn: 'Shona',
  sd: 'Sindhi',
  si: 'Sinhala, Sinhalese',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  st: 'Southern Sotho',
  es: 'Spanish, Castilian',
  su: 'Sundanese',
  sw: 'Swahili',
  ss: 'Swati',
  sv: 'Swedish',
  tl: 'Tagalog',
  ty: 'Tahitian',
  tg: 'Tajik',
  ta: 'Tamil',
  tt: 'Tatar',
  te: 'Telugu',
  th: 'Thai',
  bo: 'Tibetan',
  ti: 'Tigrinya',
  to: 'Tonga (Tonga Islands)',
  ts: 'Tsonga',
  tn: 'Tswana',
  tr: 'Turkish',
  tk: 'Turkmen',
  tw: 'Twi',
  ug: 'Uighur, Uyghur',
  uk: 'Ukrainian',
  ur: 'Urdu',
  uz: 'Uzbek',
  ve: 'Venda',
  vi: 'Vietnamese',
  vo: 'Volapük',
  wa: 'Walloon',
  cy: 'Welsh',
  wo: 'Wolof',
  xh: 'Xhosa',
  ii: 'Sichuan Yi, Nuosu',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang, Chuang',
  zu: 'Zulu',
};

const ar: languageCodeToLinguonym = {
  aa: 'لغة عفارية',
  ab: 'لغة أبخازية',
  ae: 'أفستية',
  af: 'لغة أفريقانية',
  ak: 'لغة أكانية',
  am: 'لغة أمهرية',
  an: 'لغة أراغونية',
  ar: 'لغة عربية',
  as: 'لغة آسامية',
  av: 'لغة أوارية',
  ay: 'لغة أيمارا',
  az: 'لغة أذرية',
  ba: 'لغة باشقير',
  be: 'لغة بيلاروسية',
  bg: 'لغة بلغارية',
  bi: 'لغة بسلاما',
  bm: 'لغة بمبرية',
  bn: 'لغة بنغالية، Bangla',
  bo: 'تبتية، Tibetan، Central',
  br: 'لغة بريتانية',
  bs: 'لغة بوسنوية',
  ca: 'لغة كتالانية',
  ce: 'لغة شيشانية',
  ch: 'لغة تشاموروية',
  co: 'لغة كورسية',
  cr: 'لغة كري',
  cs: 'لغة تشيكية',
  cu: 'السلافونية الكنسية القديمة، سلافونية كنسية، سلافونية كنسية قديمة',
  cv: 'لغة تشوفاش',
  cy: 'لغة ويلزية',
  da: 'لغة دنماركية',
  de: 'لغة ألمانية',
  dv: 'ديفهي، Dhivehi، Maldivian',
  dz: 'لغة دزونكا',
  ee: 'Ewe',
  el: 'لغة يونانية (حديثة)',
  en: 'لغة إنجليزية',
  eo: 'إسبرانتو',
  es: 'لغة إسبانية',
  et: 'لغة إستونية',
  eu: 'لغة بشكنشية',
  fa: 'لغة فارسية (Farsi)',
  ff: 'لغة فولانية، Fulah، Pulaar، Pular',
  fi: 'لغة فنلندية',
  fj: 'لغة فيجية',
  fo: 'لغة فاروية',
  fr: 'لغة فرنسية',
  fy: 'اللغة الفريزية الغربية',
  ga: 'لغة أيرلندية',
  gd: 'لغة غيلية إسكتلندية، Gaelic',
  gl: 'لغة غاليسية',
  gn: 'غوارانية',
  gu: 'لغة غوجاراتية',
  gv: 'لغة منكية',
  ha: 'لغة هوسية',
  he: 'لغة عبرية (حديثة)',
  hi: 'لغة هندية',
  ho: 'هيري موتو',
  hr: 'لغة كرواتية',
  ht: 'لغة كريولية هايتية، Haitian Creole',
  hu: 'لغة مجرية',
  hy: 'لغة أرمنية',
  hz: 'لغة هيريرو',
  ia: 'إنترلنغوا',
  id: 'لغة إندونيسية',
  ie: 'الغربية',
  ig: 'لغة الإيجبو',
  ii: 'Nuosu',
  ik: 'لغة إنوبياك',
  io: 'لغة إيدو',
  is: 'لغة آيسلندية',
  it: 'لغة إيطالية',
  iu: 'لغة إنكتيتوتية',
  ja: 'لغة يابانية',
  jv: 'لغة جاوية',
  ka: 'لغة جورجية',
  kg: 'لغة كونغو',
  ki: 'لغة كيكويو، Gikuyu',
  kj: 'Kwanyama، Kuanyama',
  kk: 'لغة قازاقية',
  kl: 'لغة غرينلاندية، Greenlandic',
  km: 'لغة خميرية',
  kn: 'لغة كنادية',
  ko: 'لغة كورية',
  kr: 'لغة كانورية',
  ks: 'لغة كشميرية',
  ku: 'لغة كردية',
  kv: 'لغة كومية',
  kw: 'لغة كورنية',
  ky: 'لغة قيرغيزية',
  la: 'لغة لاتينية',
  lb: 'لغة لوكسمبورغية، Letzeburgesch',
  lg: 'اللوغندية',
  li: 'لغة ليمبورغية، Limburgan، Limburger',
  ln: 'لينغالا',
  lo: 'لاو',
  lt: 'لغة ليتوانية',
  lu: 'لغة تشيلوبا',
  lv: 'لغة لاتفية',
  mg: 'لغة ملغاشية',
  mh: 'لغة مارشالية',
  mi: 'لغة ماورية',
  mk: 'لغة مقدونية',
  ml: 'لغة ماليالامية',
  mn: 'لغة منغولية',
  mr: 'لغة مراثية',
  ms: 'لغة ملايو',
  mt: 'لغة مالطية',
  my: 'لغة بورمية',
  na: 'لغة ناورونية',
  nb: 'بوكمول',
  nd: 'النديبيلية الشمالي [لغات أخرى]‏',
  ne: 'لغة نيبالية',
  ng: 'Ndonga',
  nl: 'لغة هولندية',
  nn: 'نينوشك',
  no: 'لغة نرويجية',
  nr: 'لغة نديبلي جنوبية',
  nv: 'نافاهو، Navaho',
  ny: 'لغة الشيشيوا، Chewa، Nyanja',
  oc: 'لغة قسطانية',
  oj: 'اللغة الأوجيبوية، Ojibwa',
  om: 'لغة الأورومو',
  or: 'لغة الأوريا',
  os: 'لغة أوسيتية، Ossetic',
  pa: 'لغة بنجابية، Punjabi',
  pi: 'بالية',
  pl: 'لغة بولندية',
  ps: 'لغة بشتوية، Pushto',
  pt: 'لغة برتغالية',
  qu: 'كتشوا',
  rm: 'لغة رومانشية',
  rn: 'لغة كيروندية',
  ro: 'لغة رومانية',
  ru: 'لغة روسية',
  rw: 'كينيارواندا',
  sa: 'لغة سنسكريتية',
  sc: 'لغة سردينية',
  sd: 'لغة سندية',
  se: 'لغة سامي الشمالية',
  sg: 'السانغوية',
  si: 'لغة سنهالية، Sinhalese',
  sk: 'لغة سلوفاكية',
  sl: 'لغة سلوفينية',
  sm: 'لغة ساموية',
  sn: 'لغة الشونا',
  so: 'لغة صومالية',
  sq: 'لغة ألبانية',
  sr: 'لغة صربية',
  ss: 'لغة سوازي',
  st: 'لغة سوتية',
  su: 'اللغات السوندية',
  sv: 'لغة سويدية',
  sw: 'لغة سواحلية',
  ta: 'لغة تاميلية',
  te: 'لغة تيلوغوية',
  tg: 'لغة طاجيكية',
  th: 'لغة تايلندية',
  ti: 'لغة تغرينية',
  tk: 'لغة تركمانية',
  tl: 'لغة تاغالوغية',
  tn: 'لغة تسوانية',
  to: 'التونغية (Tonga Islands)',
  tr: 'لغة تركية',
  ts: 'لغة تسونجا',
  tt: 'لغة تترية',
  tw: 'توي',
  ty: 'لغة تاهيتية',
  ug: 'لغة أويغورية',
  uk: 'لغة أوكرانية',
  ur: 'لغة أردوية',
  uz: 'لغة أوزبكية',
  ve: 'لغة فيندية',
  vi: 'لغة فيتنامية',
  vo: 'فولابوك',
  wa: 'لغة والون',
  wo: 'لغة ولوفية',
  xh: 'اللغة الخوسية',
  yi: 'لغة يديشية',
  yo: 'لغة يوربا',
  za: 'تشوانغ، Chuang',
  zh: 'لغة صينية',
  zu: 'لغة زولوية',
};

const nl: languageCodeToLinguonym = {
  aa: 'Afar',
  ab: 'Abchazisch',
  ae: 'Avestisch',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amhaars',
  an: 'Aragonees',
  ar: 'Arabisch',
  as: 'Assamees',
  av: 'Avaars',
  ay: 'Aymara',
  az: 'Azerbeidzjaans',
  ba: 'Basjkiers',
  be: 'Wit-Russisch (Belarussisch)',
  bg: 'Bulgaars',
  bi: 'Bislama',
  bm: 'Bambara',
  bn: 'Bengaals',
  bo: 'Tibetaans',
  br: 'Bretons',
  bs: 'Bosnisch',
  ca: 'Catalaans',
  ce: 'Tsjetsjeens',
  ch: 'Chamorro',
  co: 'Corsicaans',
  cr: 'Cree',
  cs: 'Tsjechisch',
  cu: 'Kerkslavisch',
  cv: 'Tsjoevasjisch',
  cy: 'Welsh',
  da: 'Deens',
  de: 'Duits',
  dv: 'Divehi',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Grieks',
  en: 'Engels',
  eo: 'Esperanto',
  es: 'Spaans',
  et: 'Estisch',
  eu: 'Baskisch',
  fa: 'Perzisch (Farsi)',
  ff: 'Fula',
  fi: 'Fins',
  fj: 'Fijisch',
  fo: 'Faeröers',
  fr: 'Frans',
  fy: 'Westerlauwers Fries',
  ga: 'Iers',
  gd: 'Schots-Gaelisch',
  gl: 'Galicisch',
  gn: 'Guaraní',
  gu: 'Gujarati',
  gv: 'Manx-Gaelisch',
  ha: 'Hausa',
  he: 'Hebreeuws',
  hi: 'Hindi',
  ho: 'Hiri Motu',
  hr: 'Kroatisch',
  ht: 'Haïtiaans-Creools',
  hu: 'Hongaars',
  hy: 'Armeens',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonesisch',
  ie: 'Interlingue',
  ig: 'Igbo',
  ii: 'Yi',
  ik: 'Inupiak',
  io: 'Ido',
  is: 'IJslands',
  it: 'Italiaans',
  iu: 'Inuktitut',
  ja: 'Japans',
  jv: 'Javaans',
  ka: 'Georgisch',
  kg: 'Kongo',
  ki: 'Gikuyu',
  kj: 'Kwanyama',
  kk: 'Kazachs',
  kl: 'Groenlands',
  km: 'Khmer, Cambodjaans',
  kn: 'Kannada (Kanarees, Kanara)',
  ko: 'Koreaans',
  kr: 'Kanuri',
  ks: 'Kasjmiri',
  ku: 'Koerdisch',
  kv: 'Zurjeens (Komi)',
  kw: 'Cornisch',
  ky: 'Kirgizisch',
  la: 'Latijn',
  lb: 'Luxemburgs',
  lg: 'Luganda',
  li: 'Limburgs',
  ln: 'Lingala',
  lo: 'Laotiaans',
  lt: 'Litouws',
  lu: 'Luba-Katanga',
  lv: 'Lets',
  mg: 'Plateaumalagasi',
  mh: 'Marshallees',
  mi: 'Maori',
  mk: 'Macedonisch',
  ml: 'Malayalam',
  mn: 'Mongools',
  mr: 'Marathi',
  ms: 'Maleis',
  mt: 'Maltees',
  my: 'Birmaans, Birmees',
  na: 'Nauruaans',
  nb: 'Bokmål-Noors',
  nd: 'Noord-Ndebele',
  ne: 'Nepalees',
  ng: 'Ndonga',
  nl: 'Nederlands',
  nn: 'Nynorsk (Nieuw-Noors)',
  no: 'Noors',
  nr: 'Zuid-Ndebele',
  nv: 'Navajo',
  ny: 'Nyanja',
  oc: 'Occitaans',
  oj: 'Ojibweg',
  om: 'Afaan Oromo',
  or: 'Odia (Oriya)',
  os: 'Ossetisch',
  pa: 'Punjabi',
  pi: 'Pali',
  pl: 'Pools',
  ps: 'Pasjtoe',
  pt: 'Portugees',
  qu: 'Quechua',
  rm: 'Reto-Romaans',
  rn: 'Kirundi',
  ro: 'Roemeens',
  ru: 'Russisch',
  rw: 'Kinyarwanda',
  sa: 'Sanskriet',
  sc: 'Sardijns',
  sd: 'Sindhi',
  se: 'Noord-Samisch (Noord-Laps)',
  sg: 'Sango',
  si: 'Singalees',
  sk: 'Slowaaks',
  sl: 'Sloveens',
  sm: 'Samoaans',
  sn: 'Shona',
  so: 'Somalisch',
  sq: 'Albanees',
  sr: 'Servisch',
  ss: 'Swazi',
  st: 'Zuid-Sotho',
  su: 'Soendanees',
  sv: 'Zweeds',
  sw: 'Swahili',
  ta: 'Tamil',
  te: 'Telugu, Teloegoe',
  tg: 'Tadzjieks',
  th: 'Thai',
  ti: 'Tigrinya',
  tk: 'Turkmeens',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tongaans, Tonga',
  tr: 'Turks',
  ts: 'Tsonga',
  tt: 'Tataars',
  tw: 'Twi',
  ty: 'Tahitiaans',
  ug: 'Oeigoers',
  uk: 'Oekraïens',
  ur: 'Urdu',
  uz: 'Oezbeeks',
  ve: 'Venda',
  vi: 'Vietnamees',
  vo: 'Volapük, Volapuk',
  wa: 'Waals',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Jiddisch',
  yo: 'Yoruba',
  za: 'Zhuang, Tsjoeang',
  zh: 'Chinese talen',
  zu: 'Zoeloe',
};

const es: languageCodeToLinguonym = {
  aa: 'afar',
  ab: 'abjasio (o abjasiano)',
  ae: 'avéstico',
  af: 'afrikáans',
  ak: 'akano',
  am: 'amhárico',
  an: 'aragonés',
  ar: 'árabe',
  as: 'asamés',
  av: 'avar (o ávaro)',
  ay: 'aimara',
  az: 'azerí',
  ba: 'baskir',
  be: 'bielorruso',
  bg: 'búlgaro',
  bi: 'bislama',
  bm: 'bambara',
  bn: 'bengalí',
  bo: 'tibetano',
  br: 'bretón',
  bs: 'bosnio',
  ca: 'catalán',
  ce: 'checheno',
  ch: 'chamorro',
  co: 'corso',
  cr: 'cree',
  cs: 'checo',
  cu: 'eslavo eclesiástico antiguo',
  cv: 'chuvasio',
  cy: 'galés',
  da: 'danés',
  de: 'alemán',
  dv: 'maldivo (o dhivehi)',
  dz: 'dzongkha',
  ee: 'ewé',
  el: 'griego (moderno)',
  en: 'inglés',
  eo: 'esperanto',
  es: 'español (o castellano)',
  et: 'estonio',
  eu: 'euskera',
  fa: 'persa',
  ff: 'fula',
  fi: 'finés (o finlandés)',
  fj: 'fiyiano (o fiyi)',
  fo: 'feroés',
  fr: 'francés',
  fy: 'frisón (o frisio)',
  ga: 'irlandés (o gaélico)',
  gd: 'gaélico escocés',
  gl: 'gallego',
  gn: 'guaraní',
  gu: 'guyaratí (o gujaratí)',
  gv: 'manés (gaélico manés o de Isla de Man)',
  ha: 'hausa',
  he: 'hebreo',
  hi: 'hindi (o hindú)',
  ho: 'hiri motu',
  hr: 'croata',
  ht: 'haitiano',
  hu: 'húngaro',
  hy: 'armenio',
  hz: 'herero',
  ia: 'interlingua',
  id: 'indonesio',
  ie: 'occidental',
  ig: 'igbo',
  ii: 'yi de Sichuán',
  ik: 'iñupiaq',
  io: 'ido',
  is: 'islandés',
  it: 'italiano',
  iu: 'inuktitut (o inuit)',
  ja: 'japonés',
  jv: 'javanés',
  ka: 'georgiano',
  kg: 'kongo (o kikongo)',
  ki: 'kikuyu',
  kj: 'kuanyama',
  kk: 'kazajo (o kazajio)',
  kl: 'groenlandés (o kalaallisut)',
  km: 'camboyano (o jemer)',
  kn: 'canarés',
  ko: 'coreano',
  kr: 'kanuri',
  ks: 'cachemiro (o cachemir)',
  ku: 'kurdo',
  kv: 'komi',
  kw: 'córnico',
  ky: 'kirguís',
  la: 'latín',
  lb: 'luxemburgués',
  lg: 'luganda',
  li: 'limburgués',
  ln: 'lingala',
  lo: 'lao',
  lt: 'lituano',
  lu: 'luba-katanga (o chiluba)',
  lv: 'letón',
  mg: 'malgache (o malagasy)',
  mh: 'marshalés',
  mi: 'maorí',
  mk: 'macedonio',
  ml: 'malayalam',
  mn: 'mongol',
  mr: 'maratí',
  ms: 'malayo',
  mt: 'maltés',
  my: 'birmano',
  na: 'nauruano',
  nb: 'noruego bokmål',
  nd: 'ndebele del norte',
  ne: 'nepalí',
  ng: 'ndonga',
  nl: 'neerlandés (u holandés)',
  nn: 'nynorsk',
  no: 'noruego',
  nr: 'ndebele del sur',
  nv: 'navajo',
  ny: 'chichewa',
  oc: 'occitano',
  oj: 'ojibwa',
  om: 'oromo',
  or: 'oriya',
  os: 'osético (u osetio, u oseta)',
  pa: 'panyabí (o penyabi)',
  pi: 'pali',
  pl: 'polaco',
  ps: 'pastú (o pastún, o pashto)',
  pt: 'portugués',
  qu: 'quechua',
  rm: 'romanche',
  rn: 'kirundi',
  ro: 'rumano',
  ru: 'ruso',
  rw: 'ruandés (o kiñaruanda)',
  sa: 'sánscrito',
  sc: 'sardo',
  sd: 'sindhi',
  se: 'sami septentrional',
  sg: 'sango',
  si: 'cingalés',
  sk: 'eslovaco',
  sl: 'esloveno',
  sm: 'samoano',
  sn: 'shona',
  so: 'somalí',
  sq: 'albanés',
  sr: 'serbio',
  ss: 'suazi (o swati, o siSwati)',
  st: 'sesotho',
  su: 'sundanés (o sondanés)',
  sv: 'sueco',
  sw: 'suajili',
  ta: 'tamil',
  te: 'télugu',
  tg: 'tayiko',
  th: 'tailandés',
  ti: 'tigriña',
  tk: 'turcomano',
  tl: 'tagalo',
  tn: 'setsuana',
  to: 'tongano',
  tr: 'turco',
  ts: 'tsonga',
  tt: 'tártaro',
  tw: 'twi',
  ty: 'tahitiano',
  ug: 'uigur',
  uk: 'ucraniano',
  ur: 'urdu',
  uz: 'uzbeko',
  ve: 'venda',
  vi: 'vietnamita',
  vo: 'volapük',
  wa: 'valón',
  wo: 'wolof',
  xh: 'xhosa',
  yi: 'yídish (o yidis, o yiddish)',
  yo: 'yoruba',
  za: 'chuan (o chuang, o zhuang)',
  zh: 'chino',
  zu: 'zulú',
};

const fr: languageCodeToLinguonym = {
  aa: 'Afar',
  ab: 'Abkhaze',
  ae: 'Avestique',
  af: 'Afrikaans',
  ak: 'Akan',
  am: 'Amharique',
  an: 'Aragonais',
  ar: 'Arabe',
  as: 'Assamais',
  av: 'Avar',
  ay: 'Aymara',
  az: 'Azéri',
  ba: 'Bachkir',
  be: 'Biélorusse',
  bg: 'Bulgare',
  bi: 'Bichelamar',
  bm: 'Bambara',
  bn: 'Bengali',
  bo: 'Tibétain',
  br: 'Breton',
  bs: 'Bosnien',
  ca: 'Catalan',
  ce: 'Tchétchène',
  ch: 'Chamorro',
  co: 'Corse',
  cr: 'Cri',
  cs: 'Tchèque',
  cu: 'Vieux-slave',
  cv: 'Tchouvache',
  cy: 'Gallois',
  da: 'Danois',
  de: 'Allemand',
  dv: 'Maldivien',
  dz: 'Dzongkha',
  ee: 'Ewe',
  el: 'Grec moderne',
  en: 'Anglais',
  eo: 'Espéranto',
  es: 'Espagnol',
  et: 'Estonien',
  eu: 'Basque',
  fa: 'Persan',
  ff: 'Peul',
  fi: 'Finnois',
  fj: 'Fidjien',
  fo: 'Féroïen',
  fr: 'Français',
  fy: 'Frison occidental',
  ga: 'Irlandais',
  gd: 'Écossais',
  gl: 'Galicien',
  gn: 'Guarani',
  gu: 'Gujarati',
  gv: 'Mannois',
  ha: 'Haoussa',
  he: 'Hébreu',
  hi: 'Hindi',
  ho: 'Hiri motu',
  hr: 'Croate',
  ht: 'Créole haïtien',
  hu: 'Hongrois',
  hy: 'Arménien',
  hz: 'Héréro',
  ia: 'Interlingua',
  id: 'Indonésien',
  ie: 'Occidental',
  ig: 'Igbo',
  ii: 'Yi',
  ik: 'Inupiak',
  io: 'Ido',
  is: 'Islandais',
  it: 'Italien',
  iu: 'Inuktitut',
  ja: 'Japonais',
  jv: 'Javanais',
  ka: 'Géorgien',
  kg: 'Kikongo',
  ki: 'Kikuyu',
  kj: 'Kuanyama',
  kk: 'Kazakh',
  kl: 'Groenlandais',
  km: 'Khmer',
  kn: 'Kannada',
  ko: 'Coréen',
  kr: 'Kanouri',
  ks: 'Cachemiri',
  ku: 'Kurde',
  kv: 'Komi',
  kw: 'Cornique',
  ky: 'Kirghiz',
  la: 'Latin',
  lb: 'Luxembourgeois',
  lg: 'Ganda',
  li: 'Limbourgeois',
  ln: 'Lingala',
  lo: 'Lao',
  lt: 'Lituanien',
  lu: 'Luba',
  lv: 'Letton',
  mg: 'Malgache',
  mh: 'Marshallais',
  mi: 'Maori de Nouvelle-Zélande',
  mk: 'Macédonien',
  ml: 'Malayalam',
  mn: 'Mongol',
  mr: 'Marathi',
  ms: 'Malais',
  mt: 'Maltais',
  my: 'Birman',
  na: 'Nauruan',
  nb: 'Norvégien bokmål',
  nd: 'Sindebele',
  ne: 'Népalais',
  ng: 'Ndonga',
  nl: 'Néerlandais',
  nn: 'Norvégien nynorsk',
  no: 'Norvégien',
  nr: 'Nrebele',
  nv: 'Navajo',
  ny: 'Chichewa',
  oc: 'Occitan',
  oj: 'Ojibwé',
  om: 'Oromo',
  or: 'Oriya',
  os: 'Ossète',
  pa: 'Pendjabi',
  pi: 'Pali',
  pl: 'Polonais',
  ps: 'Pachto',
  pt: 'Portugais',
  qu: 'Quechua',
  rm: 'Romanche',
  rn: 'Kirundi',
  ro: 'Roumain',
  ru: 'Russe',
  rw: 'Kinyarwanda',
  sa: 'Sanskrit',
  sc: 'Sarde',
  sd: 'Sindhi',
  se: 'Same du Nord',
  sg: 'Sango',
  si: 'Cingalais',
  sk: 'Slovaque',
  sl: 'Slovène',
  sm: 'Samoan',
  sn: 'Shona',
  so: 'Somali',
  sq: 'Albanais',
  sr: 'Serbe',
  ss: 'Swati',
  st: 'Sotho du Sud',
  su: 'Soundanais',
  sv: 'Suédois',
  sw: 'Swahili',
  ta: 'Tamoul',
  te: 'Télougou',
  tg: 'Tadjik',
  th: 'Thaï',
  ti: 'Tigrigna',
  tk: 'Turkmène',
  tl: 'Tagalog',
  tn: 'Tswana',
  to: 'Tongien',
  tr: 'Turc',
  ts: 'Tsonga',
  tt: 'Tatar',
  tw: 'Twi',
  ty: 'Tahitien',
  ug: 'Ouïghour',
  uk: 'Ukrainien',
  ur: 'Ourdou',
  uz: 'Ouzbek',
  ve: 'Venda',
  vi: 'Vietnamien',
  vo: 'Volapük',
  wa: 'Wallon',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  za: 'Zhuang',
  zh: 'Chinois',
  zu: 'Zoulou',
};

const sk: languageCodeToLinguonym = {
  aa: 'Afarčina',
  ab: 'Abcházština',
  ae: 'Avestčina',
  af: 'Afrikánčina',
  ak: 'Akančina',
  am: 'Amharčina',
  an: 'Aragónčina',
  ar: 'Arabčina',
  as: 'Ásámčina',
  av: 'Avarčina',
  ay: 'Aymarčina',
  az: 'Azerčina',
  ba: 'Baskirčina',
  be: 'Bieloruština',
  bg: 'Bulharčina',
  bi: 'Bislama',
  bm: 'Bambarčina',
  bn: 'Bengálčina',
  bo: 'Tibetčina',
  br: 'Bretónčina',
  bs: 'Bosniačtina',
  ca: 'Katalánčina',
  ce: 'Čečenčina',
  ch: 'Čamorčina',
  co: 'Korzičtina',
  cr: 'Krí',
  cs: 'Čeština',
  cu: 'Cirkevná slovančina',
  cv: 'Čuvaština',
  cy: 'Waleština',
  da: 'Dánčina',
  de: 'Nemčina',
  dv: 'Divehi',
  dz: 'Dzongkä',
  ee: 'Eweština',
  el: 'Gréčtina',
  en: 'Angličtina',
  eo: 'Esperanto',
  es: 'Španielčina',
  et: 'Estónčina',
  eu: 'Baskičtina',
  fa: 'Perzština',
  ff: 'Fulbčina',
  fi: 'Fínčina',
  fj: 'Fidžijčina',
  fo: 'Faerčina',
  fr: 'Francúzština',
  fy: 'Západná frízština',
  ga: 'Írčina',
  gd: 'Škótska gaelčina',
  gl: 'Galícijčina',
  gn: 'Guaraní',
  gu: 'Gudžarátčina',
  gv: 'Mančina',
  ha: 'Hauština',
  he: 'Hebrejčina',
  hi: 'Hindčina',
  ho: 'Hiri motu',
  hr: 'Chorvátčina',
  ht: 'Haitčina',
  hu: 'Maďarčina',
  hy: 'Arménčina',
  hz: 'Herero',
  ia: 'Interlingua',
  id: 'Indonézština',
  ie: 'Interlingue',
  ig: 'Igboština',
  ii: 'S’čchuanská ioština',
  ik: 'Inupiaq',
  io: 'Ido',
  is: 'Islandčina',
  it: 'Taliančina',
  iu: 'Inuktitut',
  ja: 'Japončina',
  jv: 'Jávčina',
  ka: 'Gruzínčina',
  kg: 'Kongčina',
  ki: 'Kikuju',
  kj: 'Kuaňama',
  kk: 'Kazaština',
  kl: 'Grónska eskimáčtina',
  km: 'Kambodžská khmérčina',
  kn: 'Kannadčina',
  ko: 'Kórejčina',
  kr: 'Kanurijčina',
  ks: 'Kašmírčina',
  ku: 'Kurdčina',
  kv: 'Komijčina',
  kw: 'Kornčina',
  ky: 'Kirgizština',
  la: 'Latinčina',
  lb: 'Luxemburčina',
  lg: 'Gandčina',
  li: 'Limburčina',
  ln: 'Lingalčina',
  lo: 'Laoština',
  lt: 'Litovčina',
  lu: 'Luba-katanga',
  lv: 'Lotyština',
  mg: 'Malgaština',
  mh: 'Kajin-majol',
  mi: 'Maorijčina',
  mk: 'Macedónčina',
  ml: 'Malajálamčina',
  mn: 'Mongolčina',
  mr: 'Maráthčina',
  ms: 'Malajčina',
  mt: 'Maltčina',
  my: 'Barmčina',
  na: 'Nauru',
  nb: 'Nórsky bokmål',
  nd: 'Severné ndbele',
  ne: 'Nepálčina',
  ng: 'Ndonga',
  nl: 'Holandčina',
  nn: 'Nórsky nynorsk',
  no: 'Nórčina',
  nr: 'Južná ndebelčina',
  nv: 'Navajo',
  ny: 'Čewa',
  oc: 'Okcitánčina',
  oj: 'Odžibva',
  om: 'Oromčina',
  or: 'Uríjčina',
  os: 'Osetčina',
  pa: 'Pandžábčina',
  pi: 'Pálí',
  pl: 'Poľština',
  ps: 'Paštčina',
  pt: 'Portugalčina',
  qu: 'Kečuánčina',
  rm: 'Rétorománčina',
  rn: 'Rundčina',
  ro: 'Rumunčina',
  ru: 'Ruština',
  rw: 'Rwandčina',
  sa: 'Sanskrit',
  sc: 'Sardínčina',
  sd: 'Sindhčina',
  se: 'Severná saamčina',
  sg: 'Sango',
  si: 'Sinhalčina',
  sk: 'Slovenčina',
  sl: 'Slovinčina',
  sm: 'Samojčina',
  sn: 'Šončina',
  so: 'Somálčina',
  sq: 'Albánčina',
  sr: 'Srbčina',
  ss: 'Svazijčina',
  st: 'Južná sothčina',
  su: 'Sundčina',
  sv: 'Švédčina',
  sw: 'Swahilčina',
  ta: 'Tamilčina',
  te: 'Telugčina',
  tg: 'Tadžičtina',
  th: 'Thajčina',
  ti: 'Tigriňa',
  tk: 'Turkménčina',
  tl: 'Tagalčina',
  tn: 'Tswančina',
  to: 'Tongčina',
  tr: 'Turečtina',
  ts: 'Tsonga',
  tt: 'Tatárčina',
  tw: 'Twi',
  ty: 'Tahitčina',
  ug: 'Ujgurčina',
  uk: 'Ukrajinčina',
  ur: 'Urdčina',
  uz: 'Uzbečtina',
  ve: 'Vendčina',
  vi: 'Vietnamčina',
  vo: 'Volapük',
  wa: 'Valónčina',
  wo: 'Wolof',
  xh: 'Xhosa',
  yi: 'Jidiš',
  yo: 'Jorubčina',
  za: 'Čuangčina',
  zh: 'Čínština',
  zu: 'Zuluština',
};

const localeToLanguageNames: Record<UILanguage, languageCodeToLinguonym> = {
  en,
  ar,
  nl,
  es,
  fr,
  sk,
};

/**
 * This needs to be a service because we lean on Angular's DI to get the current
 * locale.
 */
@Injectable({
  providedIn: 'root',
})
export class GetRegistrationPreferredLanguageNameService {
  private currentLocale = inject<Locale>(LOCALE_ID);

  /**
   * Get the name for a preferred language in the locale of the current user.
   *
   * @param {string} languageCode - The ISO-639 Set 1 language code for which we want a localized name.
   * @return {string} The localized name for the preferred language.
   *
   * @example
   *
   * // returns 'German' in English locale, 'Duits' in Dutch locale etc.
   * getRegistrationPreferredLanguageName('de');
   */
  getRegistrationPreferredLanguageName(
    languageCode: RegistrationPreferredLanguage,
  ): string {
    const languageEnumLocale = getUILanguageFromLocale(this.currentLocale);
    return localeToLanguageNames[languageEnumLocale][languageCode];
  }
}
