changelog:
  exclude:
    labels:
      - dependencies # dependabot
      - ignore-for-release # manually excluded
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🛠
      labels:
        - bugfix
    - title: Other Changes
      labels:
        - '*'
