changelog:
  exclude:
    labels:
      - dependencies # dependabot
      - ignore-for-release # manually excluded
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🛠
      labels:
        - bugfix
    - title: Chores 🧹
      labels:
        - chore
    - title: Portalicious 🚀
      labels:
        - portalicious
    - title: Other Changes
      labels:
        - '*'
