# See: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - dependencies # Dependabot
      - ignore-for-release # Manually excluded
  categories:
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🛠
      labels:
        - bugfix
    - title: Other Changes 🔄
      labels:
        - other
    - title: Chores 🧹
      labels:
        - chore
