export enum AppRoutes {
  authCallback = 'auth-callback',
  changePassword = 'change-password',
  login = 'login',
  privacy = 'privacy',
  program = 'program',
  programMonitoring = 'monitoring',
  programPaymentLog = 'payment-log',
  programPayments = 'payments',
  programPaymentTransactionList = 'transaction-list',
  programRegistrationActivityLog = 'activity-log',
  programRegistrationDebitCards = 'debit-cards',
  programRegistrationPersonalInformation = 'personal-information',
  programRegistrations = 'registrations',
  programs = 'programs',
  programSettings = 'settings',
  programSettingsFsps = 'fsps',
  programSettingsInformation = 'information',
  programSettingsPaymentApproval = 'payment-approval',
  programSettingsRegistrationData = 'registration-data',
  programSettingsTeam = 'team',
  registrationByReferenceId = 'registration-by-reference-id',
  registrationLookup = 'registration-lookup',
  snake = 'snake',
  userRoles = 'user-roles',
  users = 'users',
}
