# See: https://github.com/DavidAnson/vscode-markdownlint#configure

line-length: false
code-block-style: false
no-duplicate-heading:
  siblings_only: true
no-inline-html:
  allowed_elements:
    - kbd
