# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  document-start: disable
  quoted-strings:
    quote-type: single
    required: false
    extra-allowed: []
    allow-quoted-quotes: true
  line-length: disable
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  truthy:
    check-keys: false
