import { PermissionEnum } from '@121-service/src/user/enum/permission.enum';
import { DefaultUserRole } from '@121-service/src/user/enum/user-role.enum';

export interface DefaultUserRoleDefinition {
  readonly role: DefaultUserRole;
  readonly label: string;
  readonly permissions: PermissionEnum[];
}

// Single source of truth for the default roles. These roles are read-only:
// they are created by the seed and kept in sync with this definition on every
// application startup (see PermissionMaintenanceService).
export const DEFAULT_USER_ROLES: DefaultUserRoleDefinition[] = [
  {
    role: DefaultUserRole.Admin,
    label: 'Admin',
    permissions: Object.values(PermissionEnum),
  },
  {
    role: DefaultUserRole.ProgramAdmin,
    label: 'Program Admin',
    permissions: [
      PermissionEnum.AidWorkerProgramREAD,
      PermissionEnum.AidWorkerProgramUPDATE,
      PermissionEnum.PaymentREAD,
      PermissionEnum.ProgramApprovalThresholdsREAD,
      PermissionEnum.ProgramApprovalThresholdsUPDATE,
      PermissionEnum.ProgramAttachmentsCREATE,
      PermissionEnum.ProgramAttachmentsDELETE,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.ProgramAttachmentsUPDATE,
      PermissionEnum.ProgramFspConfigCREATE,
      PermissionEnum.ProgramFspConfigDELETE,
      PermissionEnum.ProgramFspConfigREAD,
      PermissionEnum.ProgramFspConfigUPDATE,
      PermissionEnum.ProgramKoboREAD,
      PermissionEnum.ProgramKoboUPDATE,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.ProgramRegistrationAttributesCREATE,
      PermissionEnum.ProgramRegistrationAttributesDELETE,
      PermissionEnum.ProgramRegistrationAttributesUPDATE,
      PermissionEnum.ProgramUPDATE,
      PermissionEnum.RegistrationREAD,
    ],
  },
  {
    role: DefaultUserRole.View,
    label: 'Only view data, including Personally Identifiable Information',
    permissions: [
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.RegistrationNotificationREAD,
      PermissionEnum.RegistrationPersonalREAD,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
    ],
  },
  {
    role: DefaultUserRole.KoboRegistrationUser,
    label: 'Only CREATE registrations',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.RegistrationCREATE,
    ],
  },
  {
    role: DefaultUserRole.KoboValidationUser,
    label: 'Only UPDATE registrations',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.RegistrationAttributeUPDATE,
      PermissionEnum.RegistrationAttributeFinancialUPDATE,
      PermissionEnum.RegistrationPersonalUPDATE,
      PermissionEnum.RegistrationStatusMarkAsValidatedUPDATE,
    ],
  },
  {
    role: DefaultUserRole.CvaManager,
    label: 'Cash Assistance Program Manager',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramUPDATE,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.ProgramAttachmentsCREATE,
      PermissionEnum.ProgramAttachmentsDELETE,
      PermissionEnum.ProgramAttachmentsUPDATE,
      PermissionEnum.PaymentCREATE,
      PermissionEnum.PaymentDELETE,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.FspDebitCardBLOCK,
      PermissionEnum.FspDebitCardUNBLOCK,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.RegistrationCREATE,
      PermissionEnum.RegistrationAttributeUPDATE,
      PermissionEnum.RegistrationAttributeFinancialUPDATE,
      PermissionEnum.RegistrationNotificationCREATE,
      PermissionEnum.RegistrationNotificationREAD,
      PermissionEnum.RegistrationPersonalREAD,
      PermissionEnum.RegistrationPersonalEXPORT,
      PermissionEnum.RegistrationPersonalUPDATE,
      PermissionEnum.RegistrationStatusMarkAsValidatedUPDATE,
      PermissionEnum.RegistrationStatusMarkAsDeclinedUPDATE,
      PermissionEnum.RegistrationStatusIncludedUPDATE,
      PermissionEnum.RegistrationImportTemplateREAD,
      PermissionEnum.RegistrationDuplicationDELETE,
      PermissionEnum.AidWorkerProgramREAD,
      PermissionEnum.RegistrationStatusPausedUPDATE,
      PermissionEnum.RegistrationBulkUPDATE,
    ],
  },
  {
    role: DefaultUserRole.CvaOfficer,
    label: 'Cash Assistance Program Officer',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.FspDebitCardBLOCK,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.RegistrationCREATE,
      PermissionEnum.RegistrationAttributeUPDATE,
      PermissionEnum.RegistrationNotificationREAD,
      PermissionEnum.RegistrationNotificationCREATE,
      PermissionEnum.RegistrationPersonalREAD,
      PermissionEnum.RegistrationPersonalUPDATE,
      PermissionEnum.RegistrationStatusMarkAsValidatedUPDATE,
      PermissionEnum.RegistrationStatusMarkAsDeclinedUPDATE,
      PermissionEnum.RegistrationImportTemplateREAD,
      PermissionEnum.RegistrationStatusPausedUPDATE,
    ],
  },
  {
    role: DefaultUserRole.FinanceManager,
    label: 'Finance Manager',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.ProgramAttachmentsCREATE,
      PermissionEnum.PaymentCREATE,
      PermissionEnum.PaymentDELETE,
      PermissionEnum.PaymentSTART,
      PermissionEnum.PaymentRETRY,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentUPDATE,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentFspInstructionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.FspDebitCardBLOCK,
      PermissionEnum.FspDebitCardUNBLOCK,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.RegistrationPersonalREAD,
      PermissionEnum.RegistrationPaymentExport,
    ],
  },
  {
    role: DefaultUserRole.FinanceOfficer,
    label: 'Finance Officer',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.ProgramAttachmentsREAD,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentFspInstructionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.FspDebitCardBLOCK,
      PermissionEnum.FspDebitCardUNBLOCK,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.RegistrationPersonalREAD,
    ],
  },
  {
    role: DefaultUserRole.ViewWithoutPII,
    label: 'Only view data, not including Personally Identifiable Information',
    permissions: [
      PermissionEnum.ProgramREAD,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentVoucherPaperREAD,
      PermissionEnum.PaymentVoucherWhatsappREAD,
      PermissionEnum.FspDebitCardREAD,
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.RegistrationNotificationREAD,
      PermissionEnum.RegistrationREAD,
    ],
  },
  {
    role: DefaultUserRole.Approver,
    label: 'Approve payments',
    permissions: [
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.PaymentFspInstructionREAD,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.ProgramRegistrationAttributesREAD,
      PermissionEnum.RegistrationPersonalREAD,
    ],
  },
  {
    role: DefaultUserRole.ProgramTeamManager,
    label: 'Program Team Manager',
    permissions: [
      PermissionEnum.ProgramMetricsREAD,
      PermissionEnum.PaymentREAD,
      PermissionEnum.PaymentTransactionREAD,
      PermissionEnum.RegistrationREAD,
      PermissionEnum.RegistrationNotificationREAD,
      PermissionEnum.AidWorkerProgramREAD,
      PermissionEnum.AidWorkerProgramUPDATE,
    ],
  },
];
