/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AfricasTalkingNotificationDto { 
    transactionId: string;
    category: string;
    provider: string;
    providerRefId: string;
    providerChannel: string;
    clientAccount: string;
    productName: string;
    sourceType: string;
    source: string;
    destinationType: string;
    destination: string;
    value: string;
    transactionFee: string;
    providerFee: string;
    status: string;
    description: string;
    requestMetadata: object;
    providerMetadata: object;
    transactionDate: string;
}

