/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOwnerDto } from './user-owner-dto';


export interface AuditedTransactionReturnDto { 
    paymentDate: string;
    payment: number;
    referenceId: string;
    status: string;
    amount: number;
    errorMessage?: string;
    customData: object;
    fspName: string;
    fsp: string;
    fspIntegrationType: string;
    user: UserOwnerDto;
}

