/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BelcashPaymentStatusDto { 
    from: string;
    fromname: string;
    fromaccount: string;
    to: string;
    toname: string;
    toaccount: string;
    amount: number;
    fee: number;
    currency: string;
    description: string;
    statusdetail: string;
    id: string;
    date: string;
    processdate: string;
    statuscomment: string;
    status: string;
    referenceid: string;
    tracenumber: string;
    system: string;
}

