/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateMessageTemplateDto { 
    /**
     * Some types are use for registration status changes, for example: invite, include, reject and pause. Other values can be used to send custom messages.
     */
    type: string;
    language: object;
    label: object;
    message: string;
    isWhatsappTemplate: boolean;
    /**
     * Set to true if you want the template to be selectable through Send Message action in portal
     */
    isSendMessageTemplate: boolean;
}

