/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateUserRoleDto { 
    role: string;
    label: string;
    permissions: CreateUserRoleDto.PermissionsEnum;
}
export namespace CreateUserRoleDto {
    export type PermissionsEnum = 'program.update' | 'program:question.update' | 'program:question.delete' | 'program:custom-attribute.update' | 'program:metrics.read' | 'payment.read' | 'payment.create' | 'payment:fsp-instruction.read' | 'payment:transaction.read' | 'payment:voucher.read' | 'fsp:debit-card.read' | 'fsp:debit-card.block' | 'fsp:debit-card.unblock' | 'fsp:debit-card.create' | 'fsp:debit-card.export' | 'registration.read' | 'registration.create' | 'registration.delete' | 'registration:attribute.update' | 'registration:attribute:financial.update' | 'registration:fsp.update' | 'registration:notification.read' | 'registration:notification.create' | 'registration:personal.read' | 'registration:personal:for-valdation.read' | 'registration:personal.export' | 'registration:personal.update' | 'registration:status:markAsValidated.update' | 'registration:status:markAsDeclined.update' | 'registration:status:included.update' | 'registration:status:paused.update' | 'registration:import-template.read' | 'action.read' | 'action.create' | 'aid-worker:program.read' | 'aid-worker:program.update';
    export const PermissionsEnum = {
        ProgramUpdate: 'program.update' as PermissionsEnum,
        ProgramquestionUpdate: 'program:question.update' as PermissionsEnum,
        ProgramquestionDelete: 'program:question.delete' as PermissionsEnum,
        ProgramcustomAttributeUpdate: 'program:custom-attribute.update' as PermissionsEnum,
        ProgrammetricsRead: 'program:metrics.read' as PermissionsEnum,
        PaymentRead: 'payment.read' as PermissionsEnum,
        PaymentCreate: 'payment.create' as PermissionsEnum,
        PaymentfspInstructionRead: 'payment:fsp-instruction.read' as PermissionsEnum,
        PaymenttransactionRead: 'payment:transaction.read' as PermissionsEnum,
        PaymentvoucherRead: 'payment:voucher.read' as PermissionsEnum,
        FspdebitCardRead: 'fsp:debit-card.read' as PermissionsEnum,
        FspdebitCardBlock: 'fsp:debit-card.block' as PermissionsEnum,
        FspdebitCardUnblock: 'fsp:debit-card.unblock' as PermissionsEnum,
        FspdebitCardCreate: 'fsp:debit-card.create' as PermissionsEnum,
        FspdebitCardExport: 'fsp:debit-card.export' as PermissionsEnum,
        RegistrationRead: 'registration.read' as PermissionsEnum,
        RegistrationCreate: 'registration.create' as PermissionsEnum,
        RegistrationDelete: 'registration.delete' as PermissionsEnum,
        RegistrationattributeUpdate: 'registration:attribute.update' as PermissionsEnum,
        RegistrationattributefinancialUpdate: 'registration:attribute:financial.update' as PermissionsEnum,
        RegistrationfspUpdate: 'registration:fsp.update' as PermissionsEnum,
        RegistrationnotificationRead: 'registration:notification.read' as PermissionsEnum,
        RegistrationnotificationCreate: 'registration:notification.create' as PermissionsEnum,
        RegistrationpersonalRead: 'registration:personal.read' as PermissionsEnum,
        RegistrationpersonalforValdationRead: 'registration:personal:for-valdation.read' as PermissionsEnum,
        RegistrationpersonalExport: 'registration:personal.export' as PermissionsEnum,
        RegistrationpersonalUpdate: 'registration:personal.update' as PermissionsEnum,
        RegistrationstatusmarkAsValidatedUpdate: 'registration:status:markAsValidated.update' as PermissionsEnum,
        RegistrationstatusmarkAsDeclinedUpdate: 'registration:status:markAsDeclined.update' as PermissionsEnum,
        RegistrationstatusincludedUpdate: 'registration:status:included.update' as PermissionsEnum,
        RegistrationstatuspausedUpdate: 'registration:status:paused.update' as PermissionsEnum,
        RegistrationimportTemplateRead: 'registration:import-template.read' as PermissionsEnum,
        ActionRead: 'action.read' as PermissionsEnum,
        ActionCreate: 'action.create' as PermissionsEnum,
        AidWorkerprogramRead: 'aid-worker:program.read' as PermissionsEnum,
        AidWorkerprogramUpdate: 'aid-worker:program.update' as PermissionsEnum
    };
}


