/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProgramAssignmentDto { 
    roles: CreateProgramAssignmentDto.RolesEnum;
    scope: string;
}
export namespace CreateProgramAssignmentDto {
    export type RolesEnum = 'admin' | 'program-admin' | 'view' | 'view-without-PII' | 'kobo-user' | 'cva-manager' | 'cva-officer' | 'finance-manager' | 'finance-officer';
    export const RolesEnum = {
        Admin: 'admin' as RolesEnum,
        ProgramAdmin: 'program-admin' as RolesEnum,
        View: 'view' as RolesEnum,
        ViewWithoutPii: 'view-without-PII' as RolesEnum,
        KoboUser: 'kobo-user' as RolesEnum,
        CvaManager: 'cva-manager' as RolesEnum,
        CvaOfficer: 'cva-officer' as RolesEnum,
        FinanceManager: 'finance-manager' as RolesEnum,
        FinanceOfficer: 'finance-officer' as RolesEnum
    };
}


