/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinancialServiceProviderEntity { 
    fsp: string;
    displayName: object;
    integrationType: object;
    /**
     * Only relevant for integrationType=csv/xml
     */
    hasReconciliation: boolean;
    notifyOnTransaction: boolean;
}

