/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthControllerCheck200ResponseInfoValue } from './health-controller-check200-response-info-value';


export interface HealthControllerCheck503Response { 
    status?: string;
    info?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    error?: { [key: string]: HealthControllerCheck200ResponseInfoValue; } | null;
    details?: { [key: string]: HealthControllerCheck200ResponseInfoValue; };
}

