/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortingByColumnsInnerInner } from './sorting-by-columns-inner-inner';


export interface PaginatedMetaDocumented { 
    itemsPerPage: number;
    totalItems: number;
    currentPage: number;
    totalPages: number;
    sortBy?: Array<Array<SortingByColumnsInnerInner>>;
    searchBy?: Array<string>;
    search?: string;
    select?: Array<string>;
    filter?: object;
}

