/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaginatedMetaDocumented } from './paginated-meta-documented';
import { PaginatedLinksDocumented } from './paginated-links-documented';


export interface PaginatedDocumented { 
    data: Array<object>;
    meta: PaginatedMetaDocumented;
    links: PaginatedLinksDocumented;
}

