/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramReturnDto { 
    id: number;
    published: boolean;
    validation: boolean;
    location: string;
    ngo: string;
    titlePortal: object;
    description: object;
    startDate: string;
    endDate: string;
    currency: string;
    distributionFrequency: ProgramReturnDto.DistributionFrequencyEnum;
    distributionDuration: number;
    fixedTransferValue: number;
    paymentAmountMultiplierFormula: string;
    /**
     * Use the GET /financial-service-providers endpoint to find valid fspNames.
     */
    financialServiceProviders: Array<string>;
    targetNrRegistrations: number;
    tryWhatsAppFirst: boolean;
    programCustomAttributes: Array<string>;
    programQuestions: Array<string>;
    aboutProgram: object;
    /**
     * Should be array of name-related program-questions.
     */
    fullnameNamingConvention: Array<string>;
    languages: object;
    enableMaxPayments: boolean;
    enableScope: boolean;
    allowEmptyPhoneNumber: boolean;
    monitoringDashboardUrl: string;
    budget: number;
}
export namespace ProgramReturnDto {
    export type DistributionFrequencyEnum = 'week' | 'month';
    export const DistributionFrequencyEnum = {
        Week: 'week' as DistributionFrequencyEnum,
        Month: 'month' as DistributionFrequencyEnum
    };
}


