/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProgramQuestionEntity { 
    name: string;
    label: object;
    answerType: string;
    placeholder: object;
    questionType: string;
    options: object;
    scoring: object;
    persistence: boolean;
    _export: Array<string>;
    pattern: object;
    duplicateCheck: boolean;
    showInPeopleAffectedTable: boolean;
    editableInPortal: boolean;
}

