/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationStatusPatchDto { 
    status: object;
    message?: string;
    messageTemplateKey?: RegistrationStatusPatchDto.MessageTemplateKeyEnum;
}
export namespace RegistrationStatusPatchDto {
    export type MessageTemplateKeyEnum = 'registered' | 'validated' | 'included' | 'deleted' | 'completed' | 'paused' | 'declined';
    export const MessageTemplateKeyEnum = {
        Registered: 'registered' as MessageTemplateKeyEnum,
        Validated: 'validated' as MessageTemplateKeyEnum,
        Included: 'included' as MessageTemplateKeyEnum,
        Deleted: 'deleted' as MessageTemplateKeyEnum,
        Completed: 'completed' as MessageTemplateKeyEnum,
        Paused: 'paused' as MessageTemplateKeyEnum,
        Declined: 'declined' as MessageTemplateKeyEnum
    };
}


