/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateChosenFspDto { 
    newFspName: UpdateChosenFspDto.NewFspNameEnum;
    newFspAttributes: object;
}
export namespace UpdateChosenFspDto {
    export type NewFspNameEnum = 'Intersolve-voucher-whatsapp' | 'Intersolve-voucher-paper' | 'Intersolve-visa' | 'Intersolve-jumbo-physical' | 'Africas-talking' | 'BelCash' | 'VodaCash' | 'BoB-finance' | 'UkrPoshta' | 'Safaricom' | 'Commercial-bank-ethiopia' | 'Excel';
    export const NewFspNameEnum = {
        IntersolveVoucherWhatsapp: 'Intersolve-voucher-whatsapp' as NewFspNameEnum,
        IntersolveVoucherPaper: 'Intersolve-voucher-paper' as NewFspNameEnum,
        IntersolveVisa: 'Intersolve-visa' as NewFspNameEnum,
        IntersolveJumboPhysical: 'Intersolve-jumbo-physical' as NewFspNameEnum,
        AfricasTalking: 'Africas-talking' as NewFspNameEnum,
        BelCash: 'BelCash' as NewFspNameEnum,
        VodaCash: 'VodaCash' as NewFspNameEnum,
        BoBFinance: 'BoB-finance' as NewFspNameEnum,
        UkrPoshta: 'UkrPoshta' as NewFspNameEnum,
        Safaricom: 'Safaricom' as NewFspNameEnum,
        CommercialBankEthiopia: 'Commercial-bank-ethiopia' as NewFspNameEnum,
        Excel: 'Excel' as NewFspNameEnum
    };
}


