/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProgramDto { 
    published: boolean;
    location: string;
    titlePortal: object;
    ngo: string;
    startDate: string;
    endDate: string;
    currency: string;
    distributionFrequency: string;
    distributionDuration: number;
    fixedTransferValue: number;
    paymentAmountMultiplierFormula: string;
    /**
     * Use the GET /api/financial-service-providers endpoint to find valid fspNames. Any fspName supplied that is not already configured for the program, will be added. Existing FSPs are not removed from a program. Program-fsp-config is not processed. Use specific POST/PUT endpoints for that.
     */
    financialServiceProviders: Array<string>;
    targetNrRegistrations: number;
    validation: boolean;
    description: object;
    enableMaxPayments: boolean;
    enableScope: boolean;
    allowEmptyPhoneNumber: boolean;
    budget: number;
}

