/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProgramQuestionDto { 
    name: string;
    options?: Array<string>;
    scoring: object;
    persistence?: boolean;
    pattern?: string;
    showInPeopleAffectedTable: boolean;
    editableInPortal: boolean;
    _export?: object;
    placeholder?: object;
    duplicateCheck?: boolean;
    label?: object;
    answerType?: object;
    questionType?: string;
}

