/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProgramAssignmentDto { 
    rolesToAdd: UpdateProgramAssignmentDto.RolesToAddEnum;
    scope: string;
}
export namespace UpdateProgramAssignmentDto {
    export type RolesToAddEnum = 'admin' | 'program-admin' | 'view' | 'view-without-PII' | 'kobo-user' | 'cva-manager' | 'cva-officer' | 'finance-manager' | 'finance-officer';
    export const RolesToAddEnum = {
        Admin: 'admin' as RolesToAddEnum,
        ProgramAdmin: 'program-admin' as RolesToAddEnum,
        View: 'view' as RolesToAddEnum,
        ViewWithoutPii: 'view-without-PII' as RolesToAddEnum,
        KoboUser: 'kobo-user' as RolesToAddEnum,
        CvaManager: 'cva-manager' as RolesToAddEnum,
        CvaOfficer: 'cva-officer' as RolesToAddEnum,
        FinanceManager: 'finance-manager' as RolesToAddEnum,
        FinanceOfficer: 'finance-officer' as RolesToAddEnum
    };
}


