/**
 * 121-service [DEV]
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VisaCardActionLink { 
    href: string;
    action: VisaCardActionLink.ActionEnum;
    method: VisaCardActionLink.MethodEnum;
}
export namespace VisaCardActionLink {
    export type ActionEnum = 'pause' | 'unpause' | 'reissue';
    export const ActionEnum = {
        Pause: 'pause' as ActionEnum,
        Unpause: 'unpause' as ActionEnum,
        Reissue: 'reissue' as ActionEnum
    };
    export type MethodEnum = 'POST' | 'PUT';
    export const MethodEnum = {
        Post: 'POST' as MethodEnum,
        Put: 'PUT' as MethodEnum
    };
}


