import { RegistrationViewEntity } from '@121-service/src/registration/entities/registration-view.entity';
import { RegistrationAttributeTypes } from '@121-service/src/registration/enum/registration-attribute.enum';

const { numeric, text } = RegistrationAttributeTypes;

// Registration view attribute names that are ALLOWED to be filled from an
// ActivityInfo form. Attributes not in this mapping are auto-generated by 121
// and may not be supplied by the form.
export const ACTIVITY_INFO_ALLOWED_REGISTRATION_VIEW_ATTRIBUTES: Partial<
  Record<keyof RegistrationViewEntity, RegistrationAttributeTypes>
> = {
  referenceId: text,
  preferredLanguage: text,
  paymentAmountMultiplier: numeric,
  maxPayments: numeric,
  programFspConfigurationName: text,
};
