export enum SeedScript {
  pilotNL = 'pilot-nl',
  pilotNLPV = 'pilot-nl-pv',
  pilotETH = 'pilot-eth',
  pilotLBN = 'pilot-lbn',
  pilotUKR = 'pilot-ukr',
  DRC = 'drc',
  demo = 'demo',
  test = 'test',
  validation = 'validation',
  testMultiple = 'test-multiple',
  nlrcMultiple = 'nlrc-multiple',
  pilotDorcasETH = 'pilot-dorcas-eth',
  krcs = 'krcs',
}
