export enum LoggingEventCategory {
  progress = 'progress',
  input = 'input',
  ui = 'UI',
  error = 'error',
}

export enum LoggingEvent {
  accountCreated = 'account-created',
  accountDeleteFail = 'account-delete-fail',
  accountDeleteSucces = 'account-delete-succes',
  audioPause = 'audio-pause',
  audioPlay = 'audio-play',
  error = 'error',
  exception = 'exception',
  languageChosen = 'language-chosen',
  loginFail = 'login-fail',
  loginSucces = 'login-succes',
  logout = 'log-out',
  passwordInputToggle = 'password-input-toggle',
  passwordNotEqual = 'password-not-equal',
  passwordNotValid = 'password-not-valid',
  popUpOpen = 'pop-up-open',
  qaAnswerNotValid = 'qa-answer-not-valid',
  qaQuestionShown = 'qa-question-shown',
  requestRetryCancel = 'request-retry-cancel',
  requestRetryConfirm = 'request-retry-confirm',
  requestRetryQuestion = 'request-retry-question',
  sectionCompleted = 'section-completed',
  usernameNotUnique = 'username-not-unique',
  batchModeNewPa = 'batch-mode-new-pa',
}
