import { MigrationInterface, QueryRunner } from "typeorm";

export class RegistrationViewEntity1693225227963 implements MigrationInterface {
    name = 'RegistrationViewEntity1693225227963'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE INDEX "IDX_65982d6021412781740a70c895" ON "121-service"."registration_data" ("registrationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6105f577e2598f69703dc782da" ON "121-service"."registration_data" ("value") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2257d31c7aabd2568ea3093ed" ON "121-service"."registration" ("registrationProgramId") `);
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" ADD CONSTRAINT "CHK_f65115da6a1ec412cd08e97e11" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'amountPaymentsReceived', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" ADD CONSTRAINT "CHK_d26beb11bfcd9a770bdc9dec66" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'amountPaymentsReceived', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" ADD CONSTRAINT "CHK_18129cd1eb6a3fb5dd8f6da4cd" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'amountPaymentsReceived', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" ADD CONSTRAINT "CHK_418332b5db395eb904b778848e" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'amountPaymentsReceived', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."twilio_message" ADD CONSTRAINT "FK_cd56d3267e8553557ec97c6741b" FOREIGN KEY ("transactionId") REFERENCES "121-service"."transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE VIEW "121-service"."registration_view_entity" AS SELECT "registration"."id" AS "id", "registration"."programId" AS "programId", "registration"."registrationStatus" AS "status", "registration"."referenceId" AS "referenceId", "registration"."phoneNumber" AS "phoneNumber", "registration"."preferredLanguage" AS "preferredLanguage", "registration"."inclusionScore" AS "inclusionScore", "registration"."paymentAmountMultiplier" AS "paymentAmountMultiplier", "registration"."note" AS "note", "registration"."noteUpdated" AS "noteUpdated", "registration"."registrationProgramId" AS "registrationProgramId", "registration"."maxPayments" AS "maxPayments", "fsp"."fsp" AS "financialServiceProvider", "fsp"."fspDisplayNamePortal" AS "fspDisplayNamePortal" FROM "121-service"."registration" "registration" LEFT JOIN "121-service"."fsp" "fsp" ON "fsp"."id"="registration"."fspId" ORDER BY "registration"."registrationProgramId" ASC`);
        await queryRunner.query(`INSERT INTO "121-service"."typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES (DEFAULT, $1, DEFAULT, $2, $3, $4)`, ["121-service","VIEW","registration_view_entity","SELECT \"registration\".\"id\" AS \"id\", \"registration\".\"programId\" AS \"programId\", \"registration\".\"registrationStatus\" AS \"status\", \"registration\".\"referenceId\" AS \"referenceId\", \"registration\".\"phoneNumber\" AS \"phoneNumber\", \"registration\".\"preferredLanguage\" AS \"preferredLanguage\", \"registration\".\"inclusionScore\" AS \"inclusionScore\", \"registration\".\"paymentAmountMultiplier\" AS \"paymentAmountMultiplier\", \"registration\".\"note\" AS \"note\", \"registration\".\"noteUpdated\" AS \"noteUpdated\", \"registration\".\"registrationProgramId\" AS \"registrationProgramId\", \"registration\".\"maxPayments\" AS \"maxPayments\", \"fsp\".\"fsp\" AS \"financialServiceProvider\", \"fsp\".\"fspDisplayNamePortal\" AS \"fspDisplayNamePortal\" FROM \"121-service\".\"registration\" \"registration\" LEFT JOIN \"121-service\".\"fsp\" \"fsp\" ON \"fsp\".\"id\"=\"registration\".\"fspId\" ORDER BY \"registration\".\"registrationProgramId\" ASC"]);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM "121-service"."typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "schema" = $3`, ["VIEW","registration_view_entity","121-service"]);
        await queryRunner.query(`DROP VIEW "121-service"."registration_view_entity"`);
        await queryRunner.query(`ALTER TABLE "121-service"."twilio_message" DROP CONSTRAINT "FK_cd56d3267e8553557ec97c6741b"`);
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" DROP CONSTRAINT "CHK_418332b5db395eb904b778848e"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" DROP CONSTRAINT "CHK_18129cd1eb6a3fb5dd8f6da4cd"`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" DROP CONSTRAINT "CHK_d26beb11bfcd9a770bdc9dec66"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" DROP CONSTRAINT "CHK_f65115da6a1ec412cd08e97e11"`);
        await queryRunner.query(`DROP INDEX "121-service"."IDX_f2257d31c7aabd2568ea3093ed"`);
        await queryRunner.query(`DROP INDEX "121-service"."IDX_6105f577e2598f69703dc782da"`);
        await queryRunner.query(`DROP INDEX "121-service"."IDX_65982d6021412781740a70c895"`);
    }

}
