import { MigrationInterface, QueryRunner } from "typeorm";

export class PaymentCountConstraints1695632049189 implements MigrationInterface {
    name = 'PaymentCountConstraints1695632049189'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" DROP CONSTRAINT "CHK_f65115da6a1ec412cd08e97e11"`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" DROP CONSTRAINT "CHK_d26beb11bfcd9a770bdc9dec66"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" DROP CONSTRAINT "CHK_18129cd1eb6a3fb5dd8f6da4cd"`);
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" DROP CONSTRAINT "CHK_418332b5db395eb904b778848e"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" ADD CONSTRAINT "CHK_1d426fe37d1207fa9925a3988e" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'paymentCount', 'paymentCountRemaining', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" ADD CONSTRAINT "CHK_f2bd68795725d87991f93c9436" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'paymentCount', 'paymentCountRemaining', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" ADD CONSTRAINT "CHK_38922d6385e644c5bed646bd5c" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'paymentCount', 'paymentCountRemaining', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" ADD CONSTRAINT "CHK_e71cce6f501f7222fc90f3efd7" CHECK ("name" NOT IN ('id', 'status', 'referenceId', 'preferredLanguage', 'inclusionScore', 'paymentAmountMultiplier', 'note', 'noteUpdated', 'financialServiceProvider', 'registrationProgramId', 'maxPayments', 'lastTransactionCreated', 'lastTransactionPaymentNumber', 'lastTransactionStatus', 'lastTransactionAmount', 'lastTransactionErrorMessage', 'lastTransactionCustomData', 'paymentCount', 'paymentCountRemaining', 'importedDate', 'invitedDate', 'startedRegistrationDate', 'registeredWhileNoLongerEligibleDate', 'registeredDate', 'rejectionDate', 'noLongerEligibleDate', 'validationDate', 'inclusionDate', 'inclusionEndDate', 'selectedForValidationDate', 'deleteDate', 'completedDate', 'lastMessageStatus', 'lastMessageType'))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" DROP CONSTRAINT "CHK_e71cce6f501f7222fc90f3efd7"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" DROP CONSTRAINT "CHK_38922d6385e644c5bed646bd5c"`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" DROP CONSTRAINT "CHK_f2bd68795725d87991f93c9436"`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" DROP CONSTRAINT "CHK_1d426fe37d1207fa9925a3988e"`);
        await queryRunner.query(`ALTER TABLE "121-service"."monitoring_question" ADD CONSTRAINT "CHK_418332b5db395eb904b778848e" CHECK (((name)::text <> ALL ((ARRAY['id'::character varying, 'status'::character varying, 'referenceId'::character varying, 'preferredLanguage'::character varying, 'inclusionScore'::character varying, 'paymentAmountMultiplier'::character varying, 'note'::character varying, 'noteUpdated'::character varying, 'financialServiceProvider'::character varying, 'registrationProgramId'::character varying, 'maxPayments'::character varying, 'lastTransactionCreated'::character varying, 'lastTransactionPaymentNumber'::character varying, 'lastTransactionStatus'::character varying, 'lastTransactionAmount'::character varying, 'lastTransactionErrorMessage'::character varying, 'lastTransactionCustomData'::character varying, 'amountPaymentsReceived'::character varying, 'importedDate'::character varying, 'invitedDate'::character varying, 'startedRegistrationDate'::character varying, 'registeredWhileNoLongerEligibleDate'::character varying, 'registeredDate'::character varying, 'rejectionDate'::character varying, 'noLongerEligibleDate'::character varying, 'validationDate'::character varying, 'inclusionDate'::character varying, 'inclusionEndDate'::character varying, 'selectedForValidationDate'::character varying, 'deleteDate'::character varying, 'completedDate'::character varying, 'lastMessageStatus'::character varying, 'lastMessageType'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_custom_attribute" ADD CONSTRAINT "CHK_18129cd1eb6a3fb5dd8f6da4cd" CHECK (((name)::text <> ALL ((ARRAY['id'::character varying, 'status'::character varying, 'referenceId'::character varying, 'preferredLanguage'::character varying, 'inclusionScore'::character varying, 'paymentAmountMultiplier'::character varying, 'note'::character varying, 'noteUpdated'::character varying, 'financialServiceProvider'::character varying, 'registrationProgramId'::character varying, 'maxPayments'::character varying, 'lastTransactionCreated'::character varying, 'lastTransactionPaymentNumber'::character varying, 'lastTransactionStatus'::character varying, 'lastTransactionAmount'::character varying, 'lastTransactionErrorMessage'::character varying, 'lastTransactionCustomData'::character varying, 'amountPaymentsReceived'::character varying, 'importedDate'::character varying, 'invitedDate'::character varying, 'startedRegistrationDate'::character varying, 'registeredWhileNoLongerEligibleDate'::character varying, 'registeredDate'::character varying, 'rejectionDate'::character varying, 'noLongerEligibleDate'::character varying, 'validationDate'::character varying, 'inclusionDate'::character varying, 'inclusionEndDate'::character varying, 'selectedForValidationDate'::character varying, 'deleteDate'::character varying, 'completedDate'::character varying, 'lastMessageStatus'::character varying, 'lastMessageType'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "121-service"."fsp_attribute" ADD CONSTRAINT "CHK_d26beb11bfcd9a770bdc9dec66" CHECK (((name)::text <> ALL ((ARRAY['id'::character varying, 'status'::character varying, 'referenceId'::character varying, 'preferredLanguage'::character varying, 'inclusionScore'::character varying, 'paymentAmountMultiplier'::character varying, 'note'::character varying, 'noteUpdated'::character varying, 'financialServiceProvider'::character varying, 'registrationProgramId'::character varying, 'maxPayments'::character varying, 'lastTransactionCreated'::character varying, 'lastTransactionPaymentNumber'::character varying, 'lastTransactionStatus'::character varying, 'lastTransactionAmount'::character varying, 'lastTransactionErrorMessage'::character varying, 'lastTransactionCustomData'::character varying, 'amountPaymentsReceived'::character varying, 'importedDate'::character varying, 'invitedDate'::character varying, 'startedRegistrationDate'::character varying, 'registeredWhileNoLongerEligibleDate'::character varying, 'registeredDate'::character varying, 'rejectionDate'::character varying, 'noLongerEligibleDate'::character varying, 'validationDate'::character varying, 'inclusionDate'::character varying, 'inclusionEndDate'::character varying, 'selectedForValidationDate'::character varying, 'deleteDate'::character varying, 'completedDate'::character varying, 'lastMessageStatus'::character varying, 'lastMessageType'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "121-service"."program_question" ADD CONSTRAINT "CHK_f65115da6a1ec412cd08e97e11" CHECK (((name)::text <> ALL ((ARRAY['id'::character varying, 'status'::character varying, 'referenceId'::character varying, 'preferredLanguage'::character varying, 'inclusionScore'::character varying, 'paymentAmountMultiplier'::character varying, 'note'::character varying, 'noteUpdated'::character varying, 'financialServiceProvider'::character varying, 'registrationProgramId'::character varying, 'maxPayments'::character varying, 'lastTransactionCreated'::character varying, 'lastTransactionPaymentNumber'::character varying, 'lastTransactionStatus'::character varying, 'lastTransactionAmount'::character varying, 'lastTransactionErrorMessage'::character varying, 'lastTransactionCustomData'::character varying, 'amountPaymentsReceived'::character varying, 'importedDate'::character varying, 'invitedDate'::character varying, 'startedRegistrationDate'::character varying, 'registeredWhileNoLongerEligibleDate'::character varying, 'registeredDate'::character varying, 'rejectionDate'::character varying, 'noLongerEligibleDate'::character varying, 'validationDate'::character varying, 'inclusionDate'::character varying, 'inclusionEndDate'::character varying, 'selectedForValidationDate'::character varying, 'deleteDate'::character varying, 'completedDate'::character varying, 'lastMessageStatus'::character varying, 'lastMessageType'::character varying])::text[])))`);
    }

}
