# See: https://prettier.io/docs/en/options.html
#
arrowParens: always
semi: true
singleAttributePerLine: true
singleQuote: true
trailingComma: all
plugins:
  - prettier-plugin-tailwindcss
  - '@prettier/plugin-xml'
tailwindAttributes:
  - styleClass
  - icon
overrides:
  - files: '*.html'
    options:
      parser: angular
  # the following overrides are needed to fix issues with @prettier/plugin-xml
  # https://github.com/prettier/prettier/issues/17653#issuecomment-2995829311
  - files: '**/*.{ts,tsx}'
    options:
      parser: typescript
  - files: '*.xlf'
    options:
      parser: xml
      printWidth: 10000
      singleAttributePerLine: false
      htmlWhitespaceSensitivity: strict
      xmlQuoteAttributes: double
      xmlSelfClosingSpace: false
      xmlSortAttributesByKey: false
      xmlWhitespaceSensitivity: strict
