# Make sure to keep contents aligned with all other interfaces!
#
arrowParens: always
semi: true
singleAttributePerLine: true
singleQuote: true
trailingComma: all
plugins:
  - prettier-plugin-organize-imports
