# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# More specific about composite actions: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: 'E2E: Start environment'
description: Starts the pre-built Services and Portal and prepares everything needed to run the E2E-tests.

#
# Requires the artifacts `e2e-docker-images` and `e2e-portal-build`.
# See the "build-e2e-environment"-job in: ../../workflows/test_e2e_portal.yml
#
# The repository needs to be checked out before using this action.
#

inputs:
  e2eTestsPath:
    description: Location of the E2E-tests code. (relative to the repository-root)
    required: false
    default: ./e2e

runs:
  using: composite
  steps:
    - name: Set up Node.js version
      uses: actions/setup-node@v7
      with:
        node-version-file: ${{ inputs.e2eTestsPath }}/.node-version
        cache: npm
        cache-dependency-path: ${{ inputs.e2eTestsPath }}/package-lock.json

    - name: Install E2E-Tests code-dependencies
      shell: bash
      working-directory: ${{ inputs.e2eTestsPath }}
      # We only need to install the tests' dependencies, so we can skip the `postinstall`-step
      run: |
        npm ci --ignore-scripts

    - name: Set ENV-variables for test-environment
      shell: bash
      run: |
        cp services/.env.example services/.env

    - name: Download built Docker images
      uses: actions/download-artifact@v8
      with:
        name: e2e-docker-images
        path: ${{ runner.temp }}/e2e-docker-images

    - name: Load built Docker images
      shell: bash
      run: |
        docker load --input "$RUNNER_TEMP/e2e-docker-images/images.tar.gz"

    - name: Run Services with Docker
      shell: bash
      run: |
        npm run start:services:ci:prebuilt

    - name: Download built Portal
      uses: actions/download-artifact@v8
      with:
        name: e2e-portal-build
        path: interfaces/portal/www

    - name: Run Portal
      shell: bash
      working-directory: ./interfaces/portal
      run: |
        npm ci --ignore-scripts
        npm run serve:static > run-portal-logs.txt 2>&1 &

    - name: Install E2E-Tests runtime-dependencies
      shell: bash
      working-directory: ${{ inputs.e2eTestsPath }}
      run: |
        npx playwright install chromium --with-deps --no-shell

    - name: Wait for Portal
      shell: bash
      run: |
        timeout 90s sh -c 'until curl http://localhost:8088 --head --silent; do echo "Waiting for Portal to be running..."; sleep 1; done'
