export * from './callbacks-africas-talking.service';
import { CallbacksAfricasTalkingService } from './callbacks-africas-talking.service';
export * from './callbacks-belcash.service';
import { CallbacksBelcashService } from './callbacks-belcash.service';
export * from './callbacks-safaricom.service';
import { CallbacksSafaricomService } from './callbacks-safaricom.service';
export * from './financial-service-providers.service';
import { FinancialServiceProvidersService } from './financial-service-providers.service';
export * from './financial-service-providers-commercial-bank-ethiopia.service';
import { FinancialServiceProvidersCommercialBankEthiopiaService } from './financial-service-providers-commercial-bank-ethiopia.service';
export * from './financial-service-providers-intersolve-visa.service';
import { FinancialServiceProvidersIntersolveVisaService } from './financial-service-providers-intersolve-visa.service';
export * from './financial-service-providers-intersolve-voucher.service';
import { FinancialServiceProvidersIntersolveVoucherService } from './financial-service-providers-intersolve-voucher.service';
export * from './instance.service';
import { InstanceService } from './instance.service';
export * from './metrics.service';
import { MetricsService } from './metrics.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './organization.service';
import { OrganizationService } from './organization.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './programs.service';
import { ProgramsService } from './programs.service';
export * from './programs-actions.service';
import { ProgramsActionsService } from './programs-actions.service';
export * from './programs-events.service';
import { ProgramsEventsService } from './programs-events.service';
export * from './programs-registrations.service';
import { ProgramsRegistrationsService } from './programs-registrations.service';
export * from './registrations.service';
import { RegistrationsService } from './registrations.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users-assignments.service';
import { UsersAssignmentsService } from './users-assignments.service';
export const APIS = [CallbacksAfricasTalkingService, CallbacksBelcashService, CallbacksSafaricomService, FinancialServiceProvidersService, FinancialServiceProvidersCommercialBankEthiopiaService, FinancialServiceProvidersIntersolveVisaService, FinancialServiceProvidersIntersolveVoucherService, InstanceService, MetricsService, NotificationsService, OrganizationService, PaymentsService, ProgramsService, ProgramsActionsService, ProgramsEventsService, ProgramsRegistrationsService, RegistrationsService, RolesService, TransactionsService, UsersService, UsersAssignmentsService];
