# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - services/programs-service/*
pr:
  branches:
    include:
    - master
  paths:
    include:
    - services/programs-service/*

pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

steps:
- workingDirectory: services/programs-service/

- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: npm install
  displayName: Install

- script: npm test
  displayName: Tests
