export enum IntersolveVisa121ErrorText {
  createCustomerError = 'CREATE CUSTOMER ERROR',
  issueTokenError = 'ISSUE TOKEN ERROR',
  registerHolderError = 'REGISTER HOLDER ERROR',
  createPhysicalCardError = 'CREATE PHYSICAL CARD ERROR',
  getPhysicalCardError = 'GET PHYSICAL CARD ERROR',
  getTokenError = 'GET TOKEN ERROR',
  getTransactionError = 'GET TRANSACTIONS ERROR',
  linkTokenError = 'LINK TOKEN ERROR',
  transferError = 'TRANSFER ERROR',
  substituteTokenError = 'SUBSTITUTE TOKEN ERROR',
  blockTokenError = 'BLOCK TOKEN ERROR',
  updateCustomerAddressError = 'UPDATE CUSTOMER ADDRESS ERROR',
  updateCustomerIndividualNameError = 'UPDATE CUSTOMER INDIVIDUAL NAME ERROR',
  getCustomerIndividualError = 'GET CUSTOMER INDIVIDUAL ERROR',
  updatePhoneNumberError = 'UPDATE PHONE NUMBER ERROR',
  reissueCard = 'Error reissuing card',
}
