export enum IntersolveVisa121ErrorText {
  createCustomerError = 'CREATE CUSTOMER ERROR',
  issueTokenError = 'ISSUE TOKEN ERROR',
  resgisterHolderError = 'REGISTER HOLDER ERROR',
  createPhysicalCardError = 'CREATE PHYSICAL CARD ERROR',
  getPhysicalCardError = 'GET PHYSICAL CARD ERROR',
  getTokenError = 'GET TOKEN ERROR',
  getTransactionError = 'GET TRANSACTIONS ERROR',
  linkTokenError = 'LINK TOKEN ERROR',
  transferError = 'TRANSFER ERROR',
  substituteTokenError = 'SUBSTITUTE TOKEN ERROR',
  blockTokenError = 'BLOCK TOKEN ERROR',
  updatePhoneNumberError = 'UPDATE PHONE NUMBER ERROR',
  calculatingTransferAmount = 'Error calculating transfer amount',
  reissueCard = 'Error reissuing card',
}
