export enum PersonalComponents {
  createIdentity = 'create-identity',
  enrollInProgram = 'enroll-in-program',
  handleProof = 'handle-proof',
  loginIdentity = 'login-identity',
  meetingReminder = 'meeting-reminder',
  preprintedQrcode = 'preprinted-qrcode',
  selectAppointment = 'select-appointment',
  selectCountry = 'select-country',
  selectFsp = 'select-fsp',
  selectLanguage = 'select-language',
  selectProgram = 'select-program',
  setNotificationNumber = 'set-notification-number',
  signupSignin = 'signup-signin',
  storeCredential = 'store-credential',
}
