export enum PaDataTypes {
  conversationHistory = 'conversationHistory',
  country = 'countryId',
  credDefId = 'credDefId',
  credentialRequest = 'credentialRequest',
  did = 'did',
  didShort = 'didShort',
  fsp = 'fsp',
  language = 'languageCode',
  myAnswers = 'myAnswers',
  myAppointments = 'myAppointments',
  myPrograms = 'myPrograms',
  programId = 'programId',
  phoneNumber = 'phoneNumber',
  timeslot = 'timeslotChoice',
  usePreprintedQrCode = 'usePreprintedQrCode',
  username = 'username',
  wallet = 'wallet',
}
