export enum PaDataTypes {
    conversationHistory = 'conversationHistory',
    country = 'countryId',
    credDefId = 'credDefId',
    credentialRequest = 'credentialRequest',
    did = 'did',
    didShort = 'didShort',
    language = 'languageCode',
    myAnswers = 'myAnswers',
    myAppointments = 'myAppointments',
    myPrograms = 'myPrograms',
    programId = 'programId',
    timeslot = 'timeslotChoice',
    wallet = 'wallet',
}
