import { CurrencyCode } from '@121-service/src/exchange-rates/enums/currency-code.enum';

export const getCurrencySymbol = ({ code }: { code: CurrencyCode }): string => {
  const currencyPart = new Intl.NumberFormat(CURRENCY_HOME_LOCALES[code], {
    style: 'currency',
    currency: code,
    currencyDisplay: 'narrowSymbol',
  })
    .formatToParts(0)
    .find((part) => part.type === 'currency');

  // If the currency symbol is not supported by the font, it may appear as a special character or zero-width space.

  const SOM_SIGN_WITHOUT_FONT_SUPPORT = '\u20C0';
  const ZERO_WIDTH_SPACE = '\u200B';

  // In these edge cases we just return the currency code.

  if (
    !currencyPart?.value ||
    currencyPart.value === SOM_SIGN_WITHOUT_FONT_SUPPORT ||
    currencyPart.value === ZERO_WIDTH_SPACE
  ) {
    return code;
  }

  return currencyPart.value;
};

// Intl has no currency-to-locale data; shared currencies (EUR, XOF, XAF, USD, ...) use one representative locale.
const CURRENCY_HOME_LOCALES: Record<CurrencyCode, string> = {
  [CurrencyCode.AED]: 'ar-AE',
  [CurrencyCode.AFN]: 'fa-AF',
  [CurrencyCode.ALL]: 'sq-AL',
  [CurrencyCode.AMD]: 'hy-AM',
  [CurrencyCode.ANG]: 'nl-CW',
  [CurrencyCode.AOA]: 'pt-AO',
  [CurrencyCode.ARS]: 'es-AR',
  [CurrencyCode.AUD]: 'en-AU',
  [CurrencyCode.AWG]: 'nl-AW',
  [CurrencyCode.AZN]: 'az-AZ',
  [CurrencyCode.BAM]: 'bs-BA',
  [CurrencyCode.BBD]: 'en-BB',
  [CurrencyCode.BDT]: 'bn-BD',
  [CurrencyCode.BGN]: 'bg-BG',
  [CurrencyCode.BHD]: 'ar-BH',
  [CurrencyCode.BIF]: 'fr-BI',
  [CurrencyCode.BMD]: 'en-BM',
  [CurrencyCode.BND]: 'ms-BN',
  [CurrencyCode.BOB]: 'es-BO',
  [CurrencyCode.BRL]: 'pt-BR',
  [CurrencyCode.BSD]: 'en-BS',
  [CurrencyCode.BTN]: 'en-BT',
  [CurrencyCode.BWP]: 'en-BW',
  [CurrencyCode.BYN]: 'ru-BY',
  [CurrencyCode.BZD]: 'en-BZ',
  [CurrencyCode.CAD]: 'en-CA',
  [CurrencyCode.CDF]: 'fr-CD',
  [CurrencyCode.CHF]: 'de-CH',
  [CurrencyCode.CLP]: 'es-CL',
  [CurrencyCode.CNY]: 'zh-CN',
  [CurrencyCode.COP]: 'es-CO',
  [CurrencyCode.CRC]: 'es-CR',
  [CurrencyCode.CUC]: 'es-CU',
  [CurrencyCode.CUP]: 'es-CU',
  [CurrencyCode.CVE]: 'pt-CV',
  [CurrencyCode.CZK]: 'cs-CZ',
  [CurrencyCode.DJF]: 'fr-DJ',
  [CurrencyCode.DKK]: 'da-DK',
  [CurrencyCode.DOP]: 'es-DO',
  [CurrencyCode.DZD]: 'ar-DZ',
  [CurrencyCode.EGP]: 'ar-EG',
  [CurrencyCode.ERN]: 'en-ER',
  [CurrencyCode.ETB]: 'am-ET',
  [CurrencyCode.EUR]: 'nl-NL',
  [CurrencyCode.FJD]: 'en-FJ',
  [CurrencyCode.FKP]: 'en-FK',
  [CurrencyCode.GBP]: 'en-GB',
  [CurrencyCode.GEL]: 'ka-GE',
  [CurrencyCode.GHS]: 'en-GH',
  [CurrencyCode.GIP]: 'en-GI',
  [CurrencyCode.GMD]: 'en-GM',
  [CurrencyCode.GNF]: 'fr-GN',
  [CurrencyCode.GTQ]: 'es-GT',
  [CurrencyCode.GYD]: 'en-GY',
  [CurrencyCode.HKD]: 'zh-HK',
  [CurrencyCode.HNL]: 'es-HN',
  [CurrencyCode.HRK]: 'hr-HR',
  [CurrencyCode.HTG]: 'fr-HT',
  [CurrencyCode.HUF]: 'hu-HU',
  [CurrencyCode.IDR]: 'id-ID',
  [CurrencyCode.ILS]: 'he-IL',
  [CurrencyCode.INR]: 'en-IN',
  [CurrencyCode.IQD]: 'ar-IQ',
  [CurrencyCode.IRR]: 'fa-IR',
  [CurrencyCode.ISK]: 'is-IS',
  [CurrencyCode.JMD]: 'en-JM',
  [CurrencyCode.JOD]: 'ar-JO',
  [CurrencyCode.JPY]: 'ja-JP',
  [CurrencyCode.KES]: 'en-KE',
  [CurrencyCode.KGS]: 'ky-KG',
  [CurrencyCode.KHR]: 'km-KH',
  [CurrencyCode.KMF]: 'fr-KM',
  [CurrencyCode.KPW]: 'ko-KP',
  [CurrencyCode.KRW]: 'ko-KR',
  [CurrencyCode.KWD]: 'ar-KW',
  [CurrencyCode.KYD]: 'en-KY',
  [CurrencyCode.KZT]: 'kk-KZ',
  [CurrencyCode.LAK]: 'en-LA',
  [CurrencyCode.LBP]: 'ar-LB',
  [CurrencyCode.LKR]: 'si-LK',
  [CurrencyCode.LRD]: 'en-LR',
  [CurrencyCode.LSL]: 'en-LS',
  [CurrencyCode.LYD]: 'ar-LY',
  [CurrencyCode.MAD]: 'ar-MA',
  [CurrencyCode.MDL]: 'ro-MD',
  [CurrencyCode.MGA]: 'fr-MG',
  [CurrencyCode.MKD]: 'mk-MK',
  [CurrencyCode.MMK]: 'en-MM',
  [CurrencyCode.MNT]: 'mn-MN',
  [CurrencyCode.MOP]: 'zh-MO',
  [CurrencyCode.MRU]: 'ar-MR',
  [CurrencyCode.MUR]: 'en-MU',
  [CurrencyCode.MVR]: 'en-MV',
  [CurrencyCode.MWK]: 'en-MW',
  [CurrencyCode.MXN]: 'es-MX',
  [CurrencyCode.MYR]: 'ms-MY',
  [CurrencyCode.MZN]: 'pt-MZ',
  [CurrencyCode.NAD]: 'en-NA',
  [CurrencyCode.NGN]: 'en-NG',
  [CurrencyCode.NIO]: 'es-NI',
  [CurrencyCode.NOK]: 'nb-NO',
  [CurrencyCode.NPR]: 'ne-NP',
  [CurrencyCode.NZD]: 'en-NZ',
  [CurrencyCode.OMR]: 'ar-OM',
  [CurrencyCode.PAB]: 'es-PA',
  [CurrencyCode.PEN]: 'es-PE',
  [CurrencyCode.PGK]: 'en-PG',
  [CurrencyCode.PHP]: 'en-PH',
  [CurrencyCode.PKR]: 'ur-PK',
  [CurrencyCode.PLN]: 'pl-PL',
  [CurrencyCode.PYG]: 'es-PY',
  [CurrencyCode.QAR]: 'ar-QA',
  [CurrencyCode.RON]: 'ro-RO',
  [CurrencyCode.RSD]: 'sr-RS',
  [CurrencyCode.RUB]: 'ru-RU',
  [CurrencyCode.RWF]: 'fr-RW',
  [CurrencyCode.SAR]: 'ar-SA',
  [CurrencyCode.SBD]: 'en-SB',
  [CurrencyCode.SCR]: 'en-SC',
  [CurrencyCode.SDG]: 'ar-SD',
  [CurrencyCode.SEK]: 'sv-SE',
  [CurrencyCode.SGD]: 'en-SG',
  [CurrencyCode.SHP]: 'en-SH',
  [CurrencyCode.SLL]: 'en-SL',
  [CurrencyCode.SOS]: 'so-SO',
  [CurrencyCode.SRD]: 'nl-SR',
  [CurrencyCode.SSP]: 'en-SS',
  [CurrencyCode.STN]: 'pt-ST',
  [CurrencyCode.SVC]: 'es-SV',
  [CurrencyCode.SYP]: 'ar-SY',
  [CurrencyCode.SZL]: 'en-SZ',
  [CurrencyCode.THB]: 'th-TH',
  [CurrencyCode.TJS]: 'tg-TJ',
  [CurrencyCode.TMT]: 'tk-TM',
  [CurrencyCode.TND]: 'ar-TN',
  [CurrencyCode.TOP]: 'en-TO',
  [CurrencyCode.TRY]: 'tr-TR',
  [CurrencyCode.TTD]: 'en-TT',
  [CurrencyCode.TWD]: 'zh-TW',
  [CurrencyCode.TZS]: 'sw-TZ',
  [CurrencyCode.UAH]: 'uk-UA',
  [CurrencyCode.UGX]: 'en-UG',
  [CurrencyCode.USD]: 'en-US',
  [CurrencyCode.UYU]: 'es-UY',
  [CurrencyCode.UZS]: 'uz-UZ',
  [CurrencyCode.VES]: 'es-VE',
  [CurrencyCode.VND]: 'vi-VN',
  [CurrencyCode.VUV]: 'en-VU',
  [CurrencyCode.WST]: 'en-WS',
  [CurrencyCode.XAF]: 'fr-CM',
  [CurrencyCode.XCD]: 'en-AG',
  [CurrencyCode.XOF]: 'fr-SN',
  [CurrencyCode.XPF]: 'fr-PF',
  [CurrencyCode.YER]: 'ar-YE',
  [CurrencyCode.ZAR]: 'en-ZA',
  [CurrencyCode.ZMW]: 'en-ZM',
  [CurrencyCode.ZWL]: 'en-ZW',
};
