# See: https://prettier.io/docs/en/options.html
#
arrowParens: always
semi: true
singleAttributePerLine: true
singleQuote: true
trailingComma: all
plugins:
  - prettier-plugin-organize-imports
  - prettier-plugin-tailwindcss
  - '@prettier/plugin-xml'
overrides:
  - files: '*.xlf'
    options:
      parser: xml
      printWidth: 10000
      singleAttributePerLine: false
      htmlWhitespaceSensitivity: strict
      xmlQuoteAttributes: double
      xmlSelfClosingSpace: false
      xmlSortAttributesByKey: false
      xmlWhitespaceSensitivity: strict
