#!/usr/bin/env bash
#
# git hook to run a command before actually committing when running `git commit`:
#
set -o errexit
set -o nounset
if (set -o pipefail) 2>/dev/null; then
  set -o pipefail
fi

ORANGE='\033[0;33m'
NC='\033[0m' # No Color

log() {
  printf "${ORANGE}[pre-commit]${NC} %s\n" "$1"
}

log "Running pre-commit hooks in ./husky/pre-commit"

# Prevent committing to "main"-branch:
if [ "$(git rev-parse --abbrev-ref HEAD)" = "main" ]; then
  log "You shouldn't commit directly to the main branch."
  log "Create a feature branch:  git branch new-branch-name"
  log "Then reset 'main':        git reset --hard origin/main"
  log "And continue to work:     git checkout new-branch-name"
  exit 1
fi

log "Running lint-staged"
npx lint-staged

log "Checking for changes to .env.example"
"$(dirname "$0")/scripts/warn-env-example-changes.sh"

log "All done"
