#!/usr/bin/env bash
#
# git hook to run a command before actually committing when running `git commit`:
#

ORANGE='\033[0;33m'
NC='\033[0m' # No Color

log() {
  printf "${ORANGE}[pre-commit]${NC} %s\n" "$1"
}

log "Running custom pre-commit hook defined in ./husky/pre-commit"

"$(dirname "$0")/scripts/prevent-commit-to-main.sh"

log "Running lint-staged"
npx lint-staged

"$(dirname "$0")/scripts/warn-env-example-changes.sh"

log "All done"
