# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [DRC] Interface: Portal'

env:
  workingDirectory: interfaces/Portal

permissions:
  actions: read

on:
  workflow_call:
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_PORTAL:
        required: true
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    environment: 'client-drc'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Interface
        id: build
        uses: ./.github/actions/build-interface
        with:
          interfacePath: ${{ env.workingDirectory }}
          envIcon: 'AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAANczYABjW9wD/fwAAIRDOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIzMzMzMzMzRCIzMzMzMzMkRCMzMzMzMzJEQiMzMzMzMyJEQiMzMzMzMyJEQjMzMzMzMyREIjMzMjEzMiREIjMzIzMzMiREIzIiMzMzMkRCMyMzMzMzIkQzMzMzMzMzJAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAD//wAA'
          envContentSecurityPolicy: >-
            connect-src 'self' https://drc.121.global https://westeurope-5.in.applicationinsights.azure.com https://westeurope.livediagnostics.monitor.azure.com;
            form-action https://drc.121.global;
        env:
          NG_ENV_NAME: 'DRC'
          NG_LOCALES: ${{ vars.NG_LOCALES }}
          NG_URL_121_SERVICE_API: 'https://drc.121.global/api'
          NG_AI_IKEY: '6da2af57-0ff8-4907-8e59-193e3aedc69b'
          NG_AI_ENDPOINT: 'https://westeurope-5.in.applicationinsights.azure.com/'
          APPLICATIONINSIGHTS_CONNECTION_STRING: 'InstrumentationKey=6da2af57-0ff8-4907-8e59-193e3aedc69b;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=39015109-d214-4bad-9333-f872e81a86f0'

      # More information on Static Web App workflow configurations,
      # See: https://aka.ms/swaworkflowconfig
      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTAL }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Finish
        run: |
          echo "Build version: ${{ steps.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY
