# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [Ethiopia-Staging] All'

permissions:
  actions: read
  deployments: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy_service:
    name: 'Build + Deploy: 121-Service'
    uses: ./.github/workflows/deploy_client-ethiopia-staging_service.yml
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
