# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [staging] Interface: Portal'

env:
  workingDirectory: interfaces/Portal

permissions:
  actions: read

on:
  workflow_call:
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MEADOW_013E37403:
        required: true
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Interface
        id: build
        uses: ./.github/actions/build-interface
        with:
          interfacePath: ${{ env.workingDirectory }}
          envContentSecurityPolicy: >-
            connect-src 'self' https://staging.121.global https://westeurope-1.in.applicationinsights.azure.com https://westeurope.livediagnostics.monitor.azure.com https://*.ciamlogin.com;
            form-action https://staging.121.global;
            frame-src blob: 'self' https://app.powerbi.com https://*.ciamlogin.com;
            frame-ancestors 'self' https://flex.twilio.com;
        env:
          NG_ENV_NAME: 'staging'
          NG_LOCALES: ${{ vars.NG_LOCALES }}
          NG_URL_121_SERVICE_API: 'https://staging.121.global/api'
          NG_AI_IKEY: '27eaf00e-92e5-46b7-8d0b-1b413db898e7'
          NG_AI_ENDPOINT: 'https://westeurope-1.in.applicationinsights.azure.com/'
          APPLICATIONINSIGHTS_CONNECTION_STRING: 'InstrumentationKey=27eaf00e-92e5-46b7-8d0b-1b413db898e7;IngestionEndpoint=https://westeurope-1.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/'
          USE_SSO_AZURE_ENTRA: ${{ vars.USE_SSO_AZURE_ENTRA }}
          AZURE_ENTRA_CLIENT_ID: ${{ vars.AZURE_ENTRA_CLIENT_ID }}
          AZURE_ENTRA_TENANT_ID: ${{ vars.AZURE_ENTRA_TENANT_ID }}

      # More information on Static Web App workflow configurations,
      # See: https://aka.ms/swaworkflowconfig
      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MEADOW_013E37403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Finish
        run: |
          echo "Build version: ${{ steps.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY
