# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [test] Interface: Portalicious'

env:
  workingDirectory: interfaces/Portalicious

permissions:
  actions: read
  # Disabling this to avoid spamming the PR with "Your stage site is ready!" comments
  # https://github.com/Azure/static-web-apps/issues/1135#issuecomment-1750066331
  # pull-requests: write

on:
  workflow_call:
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN_PORTALICIOUS:
        required: true
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_test_portalicious.yml'
      - 'interfaces/Portalicious/**'
      - '!*.md'
      - '!*.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - '.github/workflows/deploy_test_portalicious.yml'
      - 'interfaces/Portalicious/**'
      - '!*.md'
      - '!*.yml'

jobs:
  build_and_deploy:
    name: Build and Deploy Job
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    environment: 'test'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Interface
        id: build
        uses: ./.github/actions/build-interface
        with:
          interfacePath: ${{ env.workingDirectory }}
          envIcon: 'AAABAAEAEBAAAAAAAABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAgAsMjP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwoNPygsLf8AAAAAJysrXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHCEg/xETEv4xMS37KiwqigECAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJCQjsNTs9/zk6OP87PDj/bXd5/2Fra/8+QUD/NDMrSgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyMi/+PTw6/z4+O/+Bi4z/Oz06/ywuK/9JTUz/PkA8/zw/Pf9eYmHaAAAAAAAAAAAAAAAAAAAAABEVFMKYoaL/NDUy/yEjIf8jJCL/Pj89/296e/85Ojj/DxAR/xccHP9LUFD/QEE7/xQVFgAAAAAAAAAAAAAAAAAwNTUjMTIw/zY2NP8xMzD/Ojs6/zQ2M/8dHx7/6VYj/+1GH/8ZGxv/LjUz/3eChf+Ik5f/AAAAAAAAAAAAAAAAWF9eii4yMv83ODb/OTo4/x8eG/8dHxz/WyAN//z7e//8/LD/wkYf/wMDA/+IlJX/TVNU/wAAAAAAAAAAAAAAAFplZutQWFj/UVZU/0BDQf9ESUj/QkA5/xgPDf/4fjT//Pp1/8pHH/8cHh7/anV2/1liYv8xOTn/DhEPYAAAAABHUFDmICMj/2Bqa/9haGf/REdG/0REQf9KTEr/EQcF/1YZCv+fq63/W2Ji/7G/wv9/jJD/AAAAAAAAAABCSkvfBgcJAAAAAP8lKSj/a3d5/3N+f/85QUH/ZGts/4KNjv+Om57/scHE/3KAhP86QUD/tsnO/wAAAABtcnHBAAAAAAAAAAAOERLoHSIj/2l2ef+NnJ//jZ6g/1ZgYf9MU1L/hJCR/4SRk//P5er/2vD3/wAAAAAYGhv/AAAAAAAAAAAAAAAAAAAAAAUFBP9OWVv/rMbM/7PM0P+WqK3/rsbN/5moq//8/v7/+fv7/7fP1WBSWFr+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw8N/563vP/q/v7/xePr/7jR2f+KnKH/4/3+/xMVFfZrdHY4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyPT0FxuXv/x0gIP+wy9L/pK2uKFVaWf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhISEBPEJF60lRVDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/78AAP7/AAD4fwAA4D8AAMAPAAAADwAAgAcAAAAHAAAAAwAAAAYAAIAFAACACwAAwBcAAOAfAAD4vwAA/v8AAA=='
          envIconPath: 'public/favicon.ico'
          envContentSecurityPolicy: >-
            connect-src 'self' https://test.121.global https://westeurope-5.in.applicationinsights.azure.com https://westeurope.livediagnostics.monitor.azure.com https://*.ciamlogin.com;
            form-action https://test.121.global;
            frame-src blob: 'self' https://app.powerbi.com https://*.ciamlogin.com;
            frame-ancestors 'self' https://flex.twilio.com;
            style-src 'self' https://fonts.googleapis.com;
            font-src 'self' https://fonts.gstatic.com;
        env:
          NG_ENV_NAME: 'test'
          NG_LOCALES: 'en,nl'
          NG_URL_121_SERVICE_API: 'https://test.121.global/api'
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ vars.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          USE_SSO_AZURE_ENTRA: ${{ vars.USE_SSO_AZURE_ENTRA }}
          AZURE_ENTRA_CLIENT_ID: ${{ vars.AZURE_ENTRA_CLIENT_ID }}
          AZURE_ENTRA_TENANT_ID: ${{ vars.AZURE_ENTRA_TENANT_ID }}

      # More information on Static Web App workflow configurations,
      # See: https://aka.ms/swaworkflowconfig
      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTALICIOUS }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Finish
        run: |
          echo "Build version: ${{ steps.build.outputs.build_version }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'test'
    steps:
      - name: 'Close Pull Request: Deploy to Azure Static Web App'
        uses: Azure/static-web-apps-deploy@v1
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: true
        with:
          app_location: '${{ env.workingDirectory }}/www'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PORTALICIOUS }}
          action: 'close'
