# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Also, see: https://github.com/Azure/actions-workflow-samples

name: 'Deploy [test] Mock-Service'

env:
  AZURE_WEBAPP_NAME: '121-mock'
  AZURE_WEBAPP_PACKAGE_PATH: services/mock-service

defaults:
  run:
    working-directory: services/mock-service

permissions:
  actions: read

on:
  workflow_call:
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE_MOCK_SERVICE:
        required: true
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_test_mock-service.yml'
      - 'services/mock-service/**'
      - '!*.md'
      - '!*.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          # See supported Node.js versions: https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/node_support.md
          node-version-file: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/package-lock.json'

      - name: Install
        run: npm ci --no-fund --no-audit

      - name: Build
        shell: bash
        run: 'npm run build'

      - name: Creating ZIP package
        run: zip --quiet --display-globaldots --recurse-paths artifact.zip .

      - name: Deploy to Azure App Service
        id: deploy_to_aas
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_MOCK_SERVICE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/artifact.zip'
          type: zip
          clean: true

      - name: Finish
        run: |
          echo "Preview: <${{ steps.deploy_to_aas.outputs.webapp-url }}>" >> $GITHUB_STEP_SUMMARY
