# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy Portal + Service for Demo & Training'

permissions:
  actions: read
  deployments: write

on:
  workflow_dispatch:

jobs:
  deploy_demo:
    name: 'Build + Deploy: Demo'
    uses: ./.github/workflows/deploy_client-demo_all.yml
    secrets: inherit

  deploy_training:
    name: 'Build + Deploy: Training'
    needs: deploy_demo
    uses: ./.github/workflows/deploy_client-training_all.yml
    secrets: inherit
