# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [test] Interface: PA/Registration'

env:
  workingDirectory: interfaces/PA-App

defaults:
  run:
    working-directory: interfaces/PA-App

permissions:
  actions: read
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '!.github/**'
      - '.github/workflows/deploy_test_registration.yml'
      - 'interfaces/PA-App/**'
      - '**/.vscode/*'
      - '!*.md'
      - '!*.yml'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - '!.github/**'
      - '.github/workflows/deploy_test_registration.yml'
      - 'interfaces/PA-App/**'
      - '**/.vscode/*'
      - '!*.md'
      - '!*.yml'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 'test'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '${{ env.workingDirectory }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.workingDirectory }}/package-lock.json'

      - name: Install
        env:
          HUSKY: 0
        run: 'npm ci --omit=optional --no-fund --no-audit'

      - name: Lint
        run: 'npm run lint'

      - name: Test
        run: 'npm test'

      - name: Set VERSION of build/deployment
        run: |
          echo "GLOBAL_121_VERSION=$(git describe --tags --dirty --broken)" >> $GITHUB_ENV

      - name: Build
        run: 'npm run build:prod'
        env:
          NG_PRODUCTION: 'true'
          NG_IS_DEBUG: 'false'
          NG_SHOW_DEBUG: 'false'
          NG_USE_ANIMATION: 'true'
          NG_DISABLE_TEXT_PLAYER: 'false'
          NG_ALWAYS_SHOW_TEXT_PLAYER: 'false'
          NG_USE_SERVICE_WORKER: 'true'
          NG_ENV_NAME: 'test-${{ env.GLOBAL_121_VERSION }}'
          NG_URL_121_SERVICE_API: 'https://test-vm.121.global/121-service/api'
          NG_AI_IKEY: ''
          NG_AI_ENDPOINT: ''
          APPLICATIONINSIGHTS_CONNECTION_STRING: ''

      - name: Add VERSION to deployment
        run: |
          echo "${{ env.GLOBAL_121_VERSION }}" >> www/VERSION.txt

      - name: Deploy to Azure Static Web App
        id: deploy_to_aswa
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0AF9ABD03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '${{ env.workingDirectory }}/'
          app_location: '${{ env.workingDirectory }}/www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

      - name: Finish
        run: |
          echo "Build version: ${{ env.GLOBAL_121_VERSION }}" >> $GITHUB_STEP_SUMMARY
          echo "Preview: <${{ steps.deploy_to_aswa.outputs.static_web_app_url }}>" >> $GITHUB_STEP_SUMMARY

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'test'
    steps:
      - name: 'Close Pull Request: Deploy to Azure Static Web App'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_BAY_0AF9ABD03 }}
          action: 'close'
