# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Unit & Integration Tests'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test_service_api_batches.yml
      - services/**
      - '!**.md'

defaults:
  run:
    working-directory: services

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        batch: ['1/6', '2/6', '3/6', '4/6', '5/6', '6/6']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        run: cp .env.example .env

      - name: Run Containers with Docker
        env:
          COMPOSE_BAKE: true
        run: docker compose --file=docker-compose.yml up --detach --wait --wait-timeout 300 --quiet-pull --build

      - name: Check that no new migrations are necessary
        if: ${{ matrix.batch == '6/6' }}
        run: docker compose exec 121-service npm run migration:generate src/migration/irrelevant_file_name -- --check

      - name: Run integration tests with Jest
        run: docker compose exec 121-service npm run test:integration:all -- --shard=${{ matrix.batch }}

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
