# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test: Overnight k6 load test'

on:
  schedule:
    # https://crontab.guru/#30_22_*_*_*
    - cron: '30 22 * * *'

env:
  k6TestsPath: 'k6/'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '${{ env.k6TestsPath }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.k6TestsPath }}/package-lock.json'

      - name: Set ENV-variables for test-environment
        run: |
          cp ./services/.env.example services/.env

      - name: Run Services with Docker
        working-directory: ./services
        run: |
          docker --log-level 'warn' compose -f docker-compose.yml up -d --quiet-pull --wait --wait-timeout 300

      - name: Install k6 dependencies
        working-directory: ${{ env.k6TestsPath }}
        run: |
          npm ci --omit=optional --no-fund --no-audit

      - name: Lint k6 tests
        working-directory: ${{ env.k6TestsPath }}
        run: 'npm run lint'

      - name: Download k6
        working-directory: ${{ env.k6TestsPath }}
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.51.0/k6-v0.51.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Run k6 tests
        working-directory: ${{ env.k6TestsPath }}
        run: |
          npx dotenv -e ../services/.env -- ./k6 run tests/statusChangePaymentInLargeProgram.js

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

      - name: Notify Teams
        if: always()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
                "title": "k6 Load Test Completed",
                "text": "The k6 load test job has finished. Check the logs for more details."
              }' \
          $TEAMS_WEBHOOK_URL
