# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Unit & Integration Tests'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test_service_api_batches.yml
      - .github/actions/build-service/action.yml
      - services/.env.example
      - services/121-service/**
      - services/mock-service/**
      - '!**.md'

jobs:
  test_prep:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        working-directory: services
        run: |
          cp .env.example .env

      - name: Build Containers with Docker
        working-directory: services
        run: |
          docker --log-level='warn' compose --file=docker-compose.yml build

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

  test_batches:
    runs-on: ubuntu-latest
    needs:
      - test_prep
    strategy:
      matrix:
        batch: ['1/4', '2/4', '3/4', '4/4']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        working-directory: services
        run: |
          cp .env.example .env

      - name: Build Containers with Docker
        working-directory: services
        run: |
          docker --log-level='warn' compose --file=docker-compose.yml up --detach --wait --wait-timeout 300

      - name: Run integration tests with Jest
        working-directory: services
        run: |
          docker compose exec 121-service npm run test:integration:all -- --shard=${{ matrix.batch }}

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

  test:
    runs-on: ubuntu-latest
    needs:
      - test_batches

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        working-directory: services
        run: |
          cp .env.example .env

      - name: Build Containers with Docker
        working-directory: services
        run: |
          docker --log-level='warn' compose --file=docker-compose.yml up --detach --wait --wait-timeout 300

      - name: Check that no new migrations are necessary
        working-directory: services
        run: |
          docker compose exec 121-service npm run test:migration

      - name: Run integration tests with Jest
        working-directory: services
        run: |
          docker compose exec 121-service npm run test:integration:all -- --shard=3/3

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
