# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Unit & Integration Tests'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - '.github/workflows/test_service_api.yml'
      - '.github/actions/build-service/action.yml'
      - 'services/.env.example'
      - 'services/121-service/**'
      - 'services/mock-service/**'
      - '!**.md'
  push:
    branches:
      - 'main'
      - 'release/*'
      - 'hotfix/*'
    paths:
      - '.github/workflows/test_service_api.yml'
      - '.github/actions/build-service/action.yml'
      - 'services/.env.example'
      - 'services/121-service/**'
      - 'services/mock-service/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        run: |
          cp ./services/.env.example services/.env

      - name: Unit-Test
        working-directory: ./services/121-service
        env:
          NODE_ENV: development
          TWILIO_SID: AC
          TWILIO_AUTHTOKEN: test
          TWILIO_WHATSAPP_NUMBER: 15005550006
          MOCK_TWILIO: TRUE
          MOCK_INTERSOLVE: TRUE
          MOCK_COMMERCIAL_BANK_ETHIOPIA: TRUE
          MOCK_NEDBANK: TRUE
          NEDBANK_CERTIFICATE_PATH: test

        run: |
          npm install
          npm run test:unit:coverage

      - name: Run Services with Docker
        working-directory: ./services
        run: |
          docker --log-level 'warn' compose -f docker-compose.yml up -d --quiet-pull --wait --wait-timeout 300

      - name: Check that no new migrations are necessary
        working-directory: ./services
        run: |
          docker compose exec 121-service npm run migration:generate src/migration/irrelevant_file_name -- --check

      - name: Run API tests with Jest
        working-directory: ./services
        run: |
          docker compose exec 121-service npm run test:integration:coverage

      # XXX: add some documentation to README about coverage
      - name: Generate coverage report
        working-directory: ./services/121-service
        run: |
          npm run coverage

      - uses: qltysh/qlty-action/coverage@v1
        with:
          oidc: true
          files: ./services/121-service/coverage/combined/lcov.info

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

      - name: Save coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            ./services/121-service/coverage
