# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Prettier'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.{md,json,yml,scss}'

env:
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Lint
        run: 'npm run test:prettier'
