# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Unit & Integration Tests'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test_service_api_batches.yml
      - .github/actions/build-service/action.yml
      - services/.env.example
      - services/121-service/**
      - services/mock-service/**
      - '!**.md'

defaults:
  run:
    working-directory: services

jobs:
  test_prep:
    runs-on: ubuntu-latest
    outputs:
      services_version_hash: ${{ steps.services_version.outputs.hash }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Generate version-hash of all services code
        id: services_version
        working-directory: ./
        run: echo "hash=${{ hashFiles('services/**') }}" >> $GITHUB_OUTPUT

      - name: Set ENV-variables for test-environment
        run: cp .env.example .env

      - name: Start Local Docker Registry
        run: docker run --detach -p 5000:5000 --name registry registry:2

      - name: Build and Push Docker Images
        run: |
          docker build --target production --tag localhost:5000/121-service:${{ steps.services_version.outputs.hash }} 121-service
          docker push localhost:5000/121-service:${{ steps.services_version.outputs.hash }}
          docker build --target production --tag localhost:5000/mock-service:${{ steps.services_version.outputs.hash }} mock-service
          docker push localhost:5000/mock-service:${{ steps.services_version.outputs.hash }}

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

  test_batches:
    runs-on: ubuntu-latest
    needs:
      - test_prep
    strategy:
      matrix:
        batch: ['1/4', '2/4', '3/4', '4/4']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        run: cp .env.example .env

      - name: Pull Image from Local Registry Using Folder Hash
        run: |
          docker pull localhost:5000/121-service:${{ needs.test_prep.outputs.services_version_hash }}
          docker pull localhost:5000/mock-service:${{ needs.test_prep.outputs.services_version_hash }}

      - name: Run Containers with Docker
        run: docker compose --file=docker-compose.yml up --detach --wait --wait-timeout 300 --quiet-pull --no-recreate --no-build

      - name: Run integration tests with Jest
        run: docker compose exec 121-service npm run test:integration:all -- --shard=${{ matrix.batch }}

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2

  test:
    runs-on: ubuntu-latest
    needs:
      - test_batches

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set ENV-variables for test-environment
        run: cp .env.example .env

      - name: Build Containers with Docker
        run: docker compose --file=docker-compose.yml up --detach --wait --wait-timeout 300 --quiet-pull --no-recreate --no-build

      - name: Check that no new migrations are necessary
        run: docker compose exec 121-service npm run test:migration

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
