# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Interface: Register (PA)'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'feat.*'
    paths:
      - '.github/workflows/test_interface_register.yml'
      - 'interfaces/PA-App/**'

env:
  interfacePath: 'interfaces/PA-App/'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '${{ env.interfacePath }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.interfacePath }}/package-lock.json'

      - name: Install
        working-directory: ${{ env.interfacePath }}
        run: 'npm ci --omit=optional --no-fund --no-audit'

      - name: Lint
        working-directory: ${{ env.interfacePath }}
        run: 'npm run lint'

      - name: Test
        working-directory: ${{ env.interfacePath }}
        run: 'npm test'
