# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Service: Static Checks'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test_service_code.yml
      - .github/actions/build-service/action.yml
      - services/121-service/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_service_code.yml
      - .github/actions/build-service/action.yml
      - services/121-service/**

env:
  workingDirectory: services/121-service/

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          # See supported Node.js versions: https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/node_support.md
          node-version-file: '${{ env.workingDirectory }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.workingDirectory }}/package-lock.json'

      - name: Install
        working-directory: ${{ env.workingDirectory }}
        run: 'npm ci --omit=optional'

      - name: Lint
        working-directory: ${{ env.workingDirectory }}
        run: 'npm run lint'

      - name: Check for dead code
        working-directory: ${{ env.workingDirectory }}
        run: 'npm run knip'

      - name: Check for TS errors
        working-directory: ${{ env.workingDirectory }}
        run: 'npm run typecheck'
