# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test Interface: Portal'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - .github/workflows/test_interface_portal.yml
      - interfaces/portal/**
      - services/121-service/** # 121-service's code is imported/used
  push:
    branches:
      - main
    paths:
      - .github/workflows/test_interface_portal.yml
      - interfaces/portal/**
      - services/121-service/** # 121-service's code is imported/used

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This is needed for qlty to authenticate with OIDC
# https://docs.qlty.sh/coverage/quickstart#github-actions
permissions:
  contents: read
  id-token: write

env:
  interfacePath: interfaces/portal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js version
        uses: actions/setup-node@v6
        with:
          node-version-file: '${{ env.interfacePath }}/.node-version'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install
        run: 'npm ci'

      - name: 'Test: Types'
        run: 'npm run typecheck -w portal'

      - name: Lint
        run: 'npm run lint -w portal'

      - name: Check for dead code
        run: 'npm run knip -w portal'

      - name: 'Test: Deployment Configuration'
        run: |
          cp -vf interfaces/portal/.env.example interfaces/portal/.env
          npm run build:deployment-configuration -w portal
          npm run test:deployment-configuration -w portal

      - name: 'Test: Code'
        run: 'npm run test:coverage -w portal'

      - name: 'Upload coverage report to QLTY'
        uses: qltysh/qlty-action/coverage@141b881236146435192435eb7b0e06ea0b70b4d9
        with:
          oidc: true
          add-prefix: ${{ env.interfacePath }}
          tag: portal
          files: ${{ env.interfacePath }}/coverage/portal/lcov.info

      - name: 'Check translations output-file'
        run: |
          npm run set-env-variables -w portal -- --env=development
          npm run extract-i18n -w portal
          git diff --exit-code interfaces/portal/src/locale/messages.xlf

      - name: Save coverage report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: |
            ${{ env.interfacePath }}/coverage
