# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Update Translations'

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - 'interfaces/Portal/src/assets/i18n/*.json'

jobs:
    update_translations:
        name: Update translations
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 121
              uses: actions/checkout@v2

            - name: Checkout 121-translate
              uses: actions/checkout@v2
              with:
                repository: jmargutt/121-translate
                path: translate

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r translate/requirements.txt

            - name: Update translations
              run: >
                python translate/translate-diff.py
                --key ${{ secrets.MSCOGNITIVE_KEY }}
                --assets interfaces/Portal/src/assets/i18n
              shell: sh

            - name: Commit translations
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: interfaces/Portal/src/assets/i18n/*.json
                  commit-msg: Update translations
                  github-token: ${{ secrets.REPO_TOKEN }}
