import { GenericRegistrationAttributes } from '@121-service/src/registration/enum/registration-attribute.enum';

export const ATTRIBUTE_LABELS: Record<GenericRegistrationAttributes, string> = {
  referenceId: $localize`:@@attribute-label-referenceId:Reference ID`,
  phoneNumber: $localize`:@@attribute-label-phoneNumber:Phone Number`,
  preferredLanguage: $localize`:@@attribute-label-preferredLanguage:Preferred Language`,
  paymentAmountMultiplier: $localize`:@@attribute-label-paymentAmountMultiplier:Transfer value multiplier`,
  projectFspConfigurationName: $localize`:@@attribute-label-projectFspConfigurationName:FSP`,
  projectFspConfigurationLabel: $localize`:@@attribute-label-projectFspConfigurationLabel:FSP`,
  maxPayments: $localize`:@@attribute-label-maxPayments:Max. payments`,
  paymentCount: $localize`:@@attribute-label-paymentCount:Payment Count`,
  paymentCountRemaining: $localize`:@@attribute-label-paymentCountRemaining:Remaining payments`,
  scope: $localize`:@@attribute-label-scope:Scope`,
  status: $localize`:@@attribute-label-status:Status`,
  registrationProjectId: $localize`:@@attribute-label-registrationProjectId:Registration ID`,
  created: $localize`:@@attribute-label-created:Registration Created Date`,
  inclusionScore: $localize`:@@attribute-label-inclusionScore:Inclusion Score`,
};

export const ATTRIBUTE_EDIT_INFO: Partial<
  Record<GenericRegistrationAttributes, string>
> = {
  inclusionScore: $localize`:@@attribute-edit-info-inclusionScore:Inclusion score generated by the answers of the Kobo form.`,
  maxPayments: $localize`:@@attribute-edit-info-maxPayments:Maximum amount of transfers to be received. Keeping field empty to remove the limit.`,
  paymentCountRemaining: $localize`:@@attribute-edit-info-paymentCountRemaining:This field is calculated by subtracting the sent payments from the planned payments. If the limit is removed from the planned payments this field will be empty.`,
  paymentAmountMultiplier: $localize`:@@attribute-edit-info-paymentAmountMultiplier:The transfer value will be multiplied by this number to calculate the payment amount.`,
  phoneNumber: $localize`:@@attribute-edit-info-phoneNumber:Required format: numbers only (including country-code).`,
  scope: $localize`:@@attribute-edit-info-scope:Separate the parts with a dot (i.e. 'amsterdam.west').`,
};

export const isGenericAttribute = (
  name: string,
): name is GenericRegistrationAttributes => name in ATTRIBUTE_LABELS;
